### ISSUE TITLE
crew upgrade fails on new install, removes ruby

### ISSUE THREAD

**Issue by trisk** [skycocker/chromebrew#149]
I just installed chromebrew for the first time (on CloudReady 46.1.20), and then ran `crew upgrade`:

```
chronos@localhost ~ $ sudo crew update 
From https://github.com/skycocker/chromebrew
 * branch            master     -> FETCH_HEAD
HEAD is now at 64fcdf5 Merge branch 'richard-fisher-master'
Package lists, crew, and library updated.
Checking for package updates...

ruby could be updated from 2.0.0p247 to 2.0.0p247-chromeos1

Run 'crew upgrade' to upgrade everything or 'crew upgrade <packageName>' to upgrade a specific package.
chronos@localhost ~ $ sudo crew upgrade
Updating packages...
Found ruby, version 2.0.0p247-chromeos1
Ruby removed!
Following packages also need to be installed: 
binutils gmp mpc mpfr glibc gcc make linuxheaders buildessential readline zlibpkg 
Do you agree? [Y/n]

Proceeding...
Found binutils, version 2.23.2
Package binutils already installed, skipping...
Found gmp, version 5.1.2
Package gmp already installed, skipping...
Found mpc, version 1.0.1
Package mpc already installed, skipping...
Found mpfr, version 3.1.2
Package mpfr already installed, skipping...
Found glibc, version 2.17.90-baseline
Package glibc already installed, skipping...
Found gcc, version 4.8.1-baseline
Package gcc already installed, skipping...
Found make, version 3.82
Package make already installed, skipping...
Found linuxheaders, version 3.4.0
Package linuxheaders already installed, skipping...
Found buildessential, version 1.0
Package buildessential already installed, skipping...
Found readline, version 6.2
No precompiled binary available for your platform, downloading source...
/usr/local/lib/ruby/2.0.0/uri/common.rb:176:in `split': bad URI(is not URI?):  (URI::InvalidURIError)
        from /usr/local/lib/ruby/2.0.0/uri/common.rb:211:in `parse'
        from /usr/local/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
        from /usr/local/bin/crew:137:in `download'
        from /usr/local/bin/crew:227:in `install'
        from /usr/local/bin/crew:215:in `block in resolveDependencies'
        from /usr/local/bin/crew:213:in `each'
        from /usr/local/bin/crew:213:in `resolveDependencies'
        from /usr/local/bin/crew:156:in `resolveDependenciesAndInstall'
        from /usr/local/bin/crew:118:in `block in upgrade'
        from /usr/local/bin/crew:115:in `each'
        from /usr/local/bin/crew:115:in `upgrade'
        from /usr/local/bin/crew:347:in `<main>'
chronos@localhost ~ $ sudo crew upgrade
env: ruby: No such file or directory
chronos@localhost ~ $ which ruby
which: no ruby in (/usr/local/bin:/usr/bin:/bin:/opt/bin)
chronos@localhost ~ $ which crew
/usr/local/bin/crew
```

**Comment by lyxell** [comment]
Closing as invalid, feel free to reopen.
