### ISSUE TITLE
readline can't install on i386, missing source_url

### ISSUE THREAD

**Issue by trisk** [skycocker/chromebrew#150]
Exceprt from `wget -q -O - https://raw.github.com/skycocker/chromebrew/master/install.sh | bash`

```
--2016-03-04 15:02:12--  https://dl.dropboxusercontent.com/s/mdzdoyq7dtnz682/linux-headers-3.4.0-chromeos-i686.tar.gz?token_hash=AAE4yw5oH_SfZ3lAx02mFP603rnjmoB9Gp4vqTY14NsA-A&dl=1
Resolving dl.dropboxusercontent.com... 108.160.173.69, 108.160.173.5
Connecting to dl.dropboxusercontent.com|108.160.173.69|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 738812 (721K) [application/octet-stream]
--2016-03-04 15:02:13--  https://dl.dropboxusercontent.com/s/mdzdoyq7dtnz682/linux-headers-3.4.0-chromeos-i686.tar.gz?token_hash=AAE4yw5oH_SfZ3lAx02mFP603rnjmoB9Gp4vqTY14NsA-A&dl=1
Reusing existing connection to dl.dropboxusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 738812 (721K) [application/octet-stream]
Saving to: 'linux-headers-3.4.0-chromeos-i686.tar.gz'

linux-headers-3.4.0-c 100%[========================>] 721.50K   477KB/s   in 1.5s   

2016-03-04 15:02:15 (477 KB/s) - 'linux-headers-3.4.0-chromeos-i686.tar.gz' saved [738812/738812]

Archive downloaded
Unpacking archive, this may take a while...
Installing...
Linuxheaders installed!
Found buildessential, version 1.0
Buildessential installed!
Found readline, version 6.2
No precompiled binary available for your platform, downloading source...
/usr/local/lib/ruby/2.0.0/uri/common.rb:176:in `split': bad URI(is not URI?):  (URI::InvalidURIError)
        from /usr/local/lib/ruby/2.0.0/uri/common.rb:211:in `parse'
        from /usr/local/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
        from /usr/local/bin/crew:137:in `download'
        from /usr/local/bin/crew:227:in `install'
        from /usr/local/bin/crew:159:in `resolveDependenciesAndInstall'
        from /usr/local/bin/crew:350:in `<main>'
Found git, version 1.8.4
Following packages also need to be installed: 
zlibpkg libssh2 perl curl expat gettext python 
Do you agree? [Y/n]
Proceeding...
```

Also:

```
chronos@localhost ~ $ crew install readline
Found readline, version 6.2
Following packages also need to be installed: 
binutils gmp mpc mpfr glibc gcc make linuxheaders buildessential 
Do you agree? [Y/n]

Proceeding...
Found binutils, version 2.23.2
Package binutils already installed, skipping...
Found gmp, version 5.1.2
Package gmp already installed, skipping...
Found mpc, version 1.0.1
Package mpc already installed, skipping...
Found mpfr, version 3.1.2
Package mpfr already installed, skipping...
Found glibc, version 2.17.90-baseline
Package glibc already installed, skipping...
Found gcc, version 4.8.1-baseline
Package gcc already installed, skipping...
Found make, version 3.82
Package make already installed, skipping...
Found linuxheaders, version 3.4.0
Package linuxheaders already installed, skipping...
Found buildessential, version 1.0
Package buildessential already installed, skipping...
Found readline, version 6.2
No precompiled binary available for your platform, downloading source...
/usr/local/lib/ruby/2.0.0/uri/common.rb:176:in `split': bad URI(is not URI?):  (URI::InvalidURIError)
        from /usr/local/lib/ruby/2.0.0/uri/common.rb:211:in `parse'
        from /usr/local/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
        from /usr/local/bin/crew:137:in `download'
        from /usr/local/bin/crew:227:in `install'
        from /usr/local/bin/crew:159:in `resolveDependenciesAndInstall'
        from /usr/local/bin/crew:350:in `<main>'
```

**Comment by lyxell** [comment]
i386 is not yet supported, which chromebook do you use?

**Comment by trisk** [comment]
This was a Chromium OS install (via CloudReady).

**Comment by trisk** [comment]
The package builds correctly for any platform as long as the missing source_url is set.

**Comment by lyxell** [comment]
My bad, does this work for you?
https://github.com/lyxell/chromebrew/blob/master/packages/readline.rb

**Comment by lyxell** [comment]
Closing as resolved.
