### ISSUE TITLE
[az] Unable to build

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#1791]
```
    unable to execute 'x86_64-cros-linux-gnu-clang': No such file or directory
    error: command 'x86_64-cros-linux-gnu-clang' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/tmp/crew/dest/usr/local/share/azure-cli/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-aPsZkH/scandir/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-rSkYRg-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/tmp/crew/dest/usr/local/share/azure-cli/include/site/python2.7/scandir" failed with error code 1 in /tmp/pip-build-aPsZkH/scandir/
Traceback (most recent call last):
  File "install.py", line 365, in <module>
    main()
  File "install.py", line 351, in main
    install_cli(install_dir, tmp_dir)
  File "install.py", line 140, in install_cli
    exec_command(cmd)
  File "install.py", line 100, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "/usr/local/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/tmp/crew/dest/usr/local/share/azure-cli/bin/pip', 'install', '--cache-dir', '/tmp/tmpHj0mfw', 'azure-cli', '--upgrade']' returned non-zero exit status 1
az failed to build: `python install.py` exited with 1
```

**Comment by cstrouse** [comment]
Is this still a problem for you @uberhacker? I was able to build it on x86_64.

**Comment by saltedcoffii** [comment]
az is now azure_cli and builds fine. This should be closed @uberhacker
