### ISSUE TITLE
"crew install pass" hangs indefinitely

### ISSUE THREAD

**Issue by tgevaert** [skycocker/chromebrew#2361]
## Before you submit an issue
I've looked for bugs related to this package, but don't see any.

## Description
Installing pass does not complete.  The command hangs.

If you executed a specific command:
```
>>>crew install pass
```
Output:
```
pass: The standard unix password manager           
https://www.passwordstore.org/                                           
version 1.7.1-1                                                 
*ctrl-c*
Traceback (most recent call last):               
        139: from /usr/local/bin/crew:911:in `<main>'                    
        138: from /usr/local/bin/crew:853:in `install_command'  
        137: from /usr/local/bin/crew:853:in `each'               
        136: from /usr/local/bin/crew:857:in `block in install_command'  
        135: from /usr/local/bin/crew:556:in `resolve_dependencies_and_install'
        134: from /usr/local/bin/crew:613:in `resolve_dependencies'
        133: from /usr/local/bin/crew:607:in `expand_dependencies'                    
        132: from /usr/local/bin/crew:601:in `push_dependencies'
        131: from /usr/local/bin/crew:601:in `each'
        130: from /usr/local/bin/crew:603:in `block in push_dependencies'
        131: from /usr/local/bin/crew:601:in `each'                                                                                           
        130: from /usr/local/bin/crew:603:in `block in push_dependencies'
        129: from /usr/local/bin/crew:601:in `push_dependencies'
        128: from /usr/local/bin/crew:601:in `each'
        127: from /usr/local/bin/crew:603:in `block in push_dependencies'
        126: from /usr/local/bin/crew:601:in `push_dependencies'
        125: from /usr/local/bin/crew:601:in `each'
        124: from /usr/local/bin/crew:603:in `block in push_dependencies'
        123: from /usr/local/bin/crew:601:in `push_dependencies'
        122: from /usr/local/bin/crew:601:in `each'
.......
         10: from /usr/local/bin/crew:603:in `block in push_dependencies'
          9: from /usr/local/bin/crew:601:in `push_dependencies'
          8: from /usr/local/bin/crew:601:in `each'
          7: from /usr/local/bin/crew:602:in `block in push_dependencies'
          6: from /usr/local/bin/crew:142:in `search'
          5: from /usr/local/lib64/ruby/2.5.0/find.rb:43:in `find'
          4: from /usr/local/lib64/ruby/2.5.0/find.rb:43:in `each'
          3: from /usr/local/lib64/ruby/2.5.0/find.rb:48:in `block in find'
          2: from /usr/local/lib64/ruby/2.5.0/find.rb:48:in `catch'
          1: from /usr/local/lib64/ruby/2.5.0/find.rb:51:in `block (2 levels) in find'
/usr/local/lib64/ruby/2.5.0/find.rb:51:in `lstat': Interrupt
```
## Versions and system information
chromebrew: `crew --version: 0.4.3`

ChromeOS: `cat /etc/lsb-release:`

```
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={CCBD0510-9FD5-F4B7-53CA-3EBE6CEA52D3}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={CCBD0510-9FD5-F4B7-53CA-3EBE6CEA52D3}
CHROMEOS_RELEASE_BOARD=gnawty-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=85
CHROMEOS_RELEASE_BUILDER_PATH=gnawty-release/R66-10452.85.0
CHROMEOS_RELEASE_BUILD_NUMBER=10452
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=66
CHROMEOS_RELEASE_DESCRIPTION=10452.85.0 (Official Build) stable-channel gnawty 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10452.85.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10452.85.0
```

Model: Acer Chromebook 11 CB3-131

Architecture: `uname -m: x86_64`

## Addtional information
I tried installing the two deps: `gnupg` and `tree` to see if that would help, but it did not.

What I think needs to be done:
The stack trace looks like the dependency resolution is recursing indefinitely, but I don't know how to debug ruby.

Thanks!

**Comment by uberhacker** [comment]
@tgevaert: Thank you for reporting this issue.  It appears you have run into the classic dependency infinite loop.  The problem is gnupg has pinentry as a dependency and pinentry has gnupg as a dependency.  If you remove the pinentry dependency from gnupg, that should solve the problem.  I'll try and remember to get these dependencies corrected on the next update.  Fortunately, gnupg normally has frequent releases so it should happen fairly soon.
