### ISSUE TITLE
Unable to 'crew search'

### ISSUE THREAD

**Issue by JL2210** [skycocker/chromebrew#2747]
After running `crew update`, an error occurs trying to search any package after `glfw.rb`.

```
/usr/local/lib/crew/packages/glfw.rb:18: warning: else without rescue is useless
Traceback (most recent call last):
        19: from /usr/local/bin/crew:963:in `<main>'
        18: from /usr/local/bin/crew:931:in `search_command'
        17: from /usr/local/bin/crew:116:in `list_packages'
        16: from /usr/local/lib64/ruby/2.5.0/find.rb:43:in `find'
        15: from /usr/local/lib64/ruby/2.5.0/find.rb:43:in `each'
        14: from /usr/local/lib64/ruby/2.5.0/find.rb:48:in `block in find'
        13: from /usr/local/lib64/ruby/2.5.0/find.rb:48:in `catch'
        12: from /usr/local/lib64/ruby/2.5.0/find.rb:49:in `block (2 levels) in find'
        11: from /usr/local/bin/crew:118:in `block in list_packages'
        10: from /usr/local/bin/crew:93:in `print_package'
         9: from /usr/local/bin/crew:146:in `search'
         8: from /usr/local/lib64/ruby/2.5.0/find.rb:43:in `find'
         7: from /usr/local/lib64/ruby/2.5.0/find.rb:43:in `each'
         6: from /usr/local/lib64/ruby/2.5.0/find.rb:48:in `block in find'
         5: from /usr/local/lib64/ruby/2.5.0/find.rb:48:in `catch'
         4: from /usr/local/lib64/ruby/2.5.0/find.rb:49:in `block (2 levels) in find'
         3: from /usr/local/bin/crew:147:in `block in search'
         2: from /usr/local/bin/crew:108:in `set_package'
         1: from /usr/local/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': /usr/local/lib/crew/packages/glfw.rb:14: syntax error, unexpected tIDENTIFIER, expecting keyword_when (SyntaxError)
    with 'x86_64'
    ^~~~
/usr/local/lib/crew/packages/glfw.rb:29: syntax error, unexpected keyword_end, expecting end-of-input
```

I believe this is due to a syntax error in glfw.rb. `with` is supposed to be `when`.

**Comment by uberhacker** [comment]
Yes, I was hoping @skiman6010 would merge #2745.  I'll add a high priority tag and maybe that will help. :)
