### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by Ewpratten** [skycocker/chromebrew#2945]
I am trying to use crew, and I keep getting this error.

```
Traceback (most recent call last):
        2: from /usr/local/bin/crew:86:in `<main>'
        1: from /usr/local/lib64/ruby/2.5.0/json/common.rb:156:in `parse'
/usr/local/lib64/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected token at '' (JSON::ParserError)
```

I even tried reinstalling chromebrew, but it gives the same error.

Does anyone have any suggestions on how to fix?

**Comment by Ewpratten** [comment]
Apparently removing device.json fixed this.
