### ISSUE TITLE
a minor glitch on `crew update`

### ISSUE THREAD

**Issue by nosarthur** [skycocker/chromebrew#3191]
## Description
I ran `crew update` and got some traceback. Ran it again and it was fine.

```shell
chronos (master *) blog $ crew update
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 11 (delta 9), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (11/11), done.
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
   93c767ed..749a685e  master     -> origin/master
HEAD is now at 749a685e Add pre-built binaries for musl (#3189)
Package lists, crew, and library updated.
Checking for package updates...

gdbm could be updated from 1.18 to 1.18.1
Traceback (most recent call last):
        16: from /usr/local/bin/crew:978:in `<main>'
        15: from /usr/local/bin/crew:951:in `update_command'
        14: from /usr/local/bin/crew:333:in `update'
        13: from /usr/local/bin/crew:333:in `each'
        12: from /usr/local/bin/crew:334:in `block in update'
        11: from /usr/local/bin/crew:147:in `search'
        10: from /usr/local/lib64/ruby/2.5.0/find.rb:43:in `find'
         9: from /usr/local/lib64/ruby/2.5.0/find.rb:43:in `each'
         8: from /usr/local/lib64/ruby/2.5.0/find.rb:48:in `block in find'
         7: from /usr/local/lib64/ruby/2.5.0/find.rb:48:in `catch'
         6: from /usr/local/lib64/ruby/2.5.0/find.rb:49:in `block (2 levels) in find'
         5: from /usr/local/bin/crew:148:in `block in search'
         4: from /usr/local/bin/crew:109:in `set_package'
         3: from /usr/local/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         2: from /usr/local/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         1: from /usr/local/lib/crew/packages/glibc.rb:3:in `<top (required)>'
/usr/local/lib/crew/packages/glibc.rb:7:in `<class:Glibc>': uninitialized constant Glibc::LIBC_VERSION (NameError)
```

## Versions and system information
chromebrew: `1.2.1`

ChromeOS: 
```
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=5312304
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={C166AF52-7EE9-4F08-AAA7-B4B895A9F336}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={C166AF52-7EE9-4F08-AAA7-B4B895A9F336}
CHROMEOS_RELEASE_BOARD=caroline-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=148
CHROMEOS_RELEASE_BUILDER_PATH=caroline-release/R72-11316.148.0
CHROMEOS_RELEASE_BUILD_NUMBER=11316
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=72
CHROMEOS_RELEASE_DESCRIPTION=11316.148.0 (Official Build) stable-channel caroline 
CHROMEOS_RELEASE_KEYSET=mp
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11316.148.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11316.148.0
```
Model: samsung chromebook pro

Architecture: `x86_64`

**Comment by skiman6010** [comment]
What version of `glibc` do you have installed? We just pushed an update that will install 2.27 that fixed Chrome OS 72 issues.

**Comment by uberhacker** [comment]
Thank you for the detailed issue @nosarthur.  I have noticed this also.  What I think happens is the update function tries to process before the new `const.rb` is loaded.  But what you said is correct.  If you run `crew update` again, it continues on without an issue.

**Comment by nosarthur** [comment]
`crew update` output:
```
glibc could be updated from 2.23 to 2.2x
```
Not sure why it says 2.2x

**Comment by nosarthur** [comment]
Another strange thing is that `crew update` tells me that my `buildessential could be updated from 1.3 to 1.4`. But `crew upgrade buildessential` tells me that `buildessential is already up to date.`


```
chronos / $ crew update
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 2), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
   06dae0ca..dda47947  master     -> origin/master
HEAD is now at dda47947 Update rust from 1.23.0 to 1.32.0 (#3192)
Package lists, crew, and library updated.
Checking for package updates...

gdbm could be updated from 1.18 to 1.18.1
glibc could be updated from 2.23 to 2.2x
openssl could be updated from 1.0.2p to 1.0.2p-1
buildessential could be updated from 1.3 to 1.4
bz2 could be updated from 1.0.6-2 to 1.0.6-3
libxslt could be updated from 1.14.91 to 1.1.32-1
libpng could be updated from 1.6.34 to 1.6.36
code could be updated from 1.30.2-1 to 1.31.1

Run `crew upgrade` to update all packages or `crew upgrade <package1> [<package2> ...]` to update specific packages.
chronos / $ crew upgrade buildessential
(i) buildessential: A collection of tools essential to compile and build software.

version 1.4
buildessential is already up to date.
```

**Comment by JL2210** [comment]
That's a normal issue with fake packages. It's a limitation that we can't
seem to get around.

**Comment by JL2210** [comment]
It breaks when running `crew search`, too.

**Comment by JL2210** [comment]
@nosarthur Can you please close this?

Note that solution is to run `crew update` again.
