### ISSUE TITLE
[sphinx] Unable to build

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#3944]
```
HEAD is now at 72ad5f2a9 Bump to 2.4.4 final
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /usr/local/tmp/crew/v2.4.4.tar.gz.dir/sphinx-2.4.4/build
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-nszGx1/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-nszGx1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-nszGx1/
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-nszGx1/setup.py", line 8, in <module>
        import sphinx
      File "sphinx/__init__.py", line 20, in <module>
        from .deprecation import RemovedInNextVersionWarning
      File "sphinx/deprecation.py", line 29
        def deprecated_alias(modname: str, objects: Dict, warning: Type[Warning]) -> None:
                                    ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
sphinx failed to build: `pip install . --root /usr/local/tmp/crew/dest --prefix /usr/local` exited with 1
```
Full log attached.
[sphinx.log](https://github.com/skycocker/chromebrew/files/4386667/sphinx.log)

**Comment by vincowl** [comment]
Just run `pip install --upgrade pip` It worked for me
