### ISSUE TITLE
crew update/upgrade is broken

### ISSUE THREAD

**Issue by ramsrib** [skycocker/chromebrew#3969]
## Description
When i try to  run `crew update` or `crew upgrade`, it's throwing syntax error.

If you executed a specific command:
```shell
crew update
```

Output:
```shell
chronos@localhost $ crew update
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
HEAD is now at 856d5858 [xkeyboard_config] Update to 2.29 (#3957)
Package lists, crew, and library updated.
Checking for package updates...

libxml2 could be updated from 2.9.8-2 to 2.9.9
automake could be updated from 1.16.1 to 1.16.2
expat could be updated from 2.2.6 to 2.2.9
bz2 could be updated from 1.0.6-3 to 1.0.8
xzutils could be updated from 5.2.3-2 to 5.2.5
libxslt could be updated from 1.1.32-1 to 1.1.34
libxml2_python could be updated from 2.9.8 to 2.9.9
libgcrypt could be updated from 1.8.1-1 to 1.8.5
libgpgerror could be updated from 1.31 to 1.37
docbook_xml could be updated from 4.3-1 to 5.1
gobject_introspection could be updated from 1.52.1 to 1.64.0
glib could be updated from 2.56.1 to 2.64.1
util_linux could be updated from 2.34 to 2.35.1
libpng could be updated from 1.6.36 to 1.6.37
mesa could be updated from 18.3.1-1 to 20.0.2
libva could be updated from 2.3.0 to 2.6.1
libdrm could be updated from 2.4.96 to 2.4.100
libpciaccess could be updated from 0.13-0 to 0.16
libxtrans could be updated from 1.3.5-0 to 1.4.0
libx11 could be updated from 1.6.5-1 to 1.6.9
xorg_proto could be updated from 2018.4 to 2019.2
libxcb could be updated from 1.12-0 to 1.14
xcb_proto could be updated from 1.12-0 to 1.14
libxau could be updated from 1.0.8-1 to 1.0.9
pthread_stubs could be updated from 0.3 to 0.4
freetype could be updated from 2.9.1 to 2.10
harfbuzz could be updated from 1.7.6-0 to 2.6.4
freetype_sub could be updated from 2.9 to 2.10
libxkbfile could be updated from 1.0.9-0 to 1.1.0
libvdpau could be updated from 1.1.1 to 1.3
wayland_protocols could be updated from 1.17 to 1.20
wayland could be updated from 1.16.0 to 1.18.0
elfutils could be updated from 0.177 to 0.178
swig could be updated from 3.0.12 to 4.0.1
pcre could be updated from 8.41 to 8.44
pango could be updated from 1.42.4 to 1.44.7
fribidi could be updated from 1.0.1 to 1.0.9
libjpeg could be updated from 9.0-c to 9.0-d
xkbcomp could be updated from 1.4.2 to 1.4.3
libxkbcommon could be updated from 0.9.1 to 0.10.0
Traceback (most recent call last):
        14: from /usr/local/bin/crew:1003:in `<main>'
        13: from /usr/local/bin/crew:976:in `update_command'
        12: from /usr/local/bin/crew:338:in `update'
        11: from /usr/local/bin/crew:338:in `each'
        10: from /usr/local/bin/crew:339:in `block in update'
         9: from /usr/local/bin/crew:143:in `search'
         8: from /usr/local/lib64/ruby/2.5.0/find.rb:43:in `find'
         7: from /usr/local/lib64/ruby/2.5.0/find.rb:43:in `each'
         6: from /usr/local/lib64/ruby/2.5.0/find.rb:48:in `block in find'
         5: from /usr/local/lib64/ruby/2.5.0/find.rb:48:in `catch'
         4: from /usr/local/lib64/ruby/2.5.0/find.rb:49:in `block (2 levels) in find'
         3: from /usr/local/bin/crew:144:in `block in search'
         2: from /usr/local/bin/crew:110:in `set_package'
         1: from /usr/local/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': /usr/local/lib/crew/packages/xkeyboard_config.rb:22: syntax error, unexpected tIDENTIFIER, expecting keyword_end (SyntaxError)
.../rules/compat/map-variants.py"i
...                              ^
```

Similar error for `crew upgrade`:
```shell
chronos@localhost $ crew upgrade
Traceback (most recent call last):
        30: from /usr/local/bin/crew:1003:in `<main>'
        29: from /usr/local/bin/crew:986:in `upgrade_command'
        28: from /usr/local/bin/crew:374:in `upgrade'
        27: from /usr/local/bin/crew:374:in `each'
        26: from /usr/local/bin/crew:381:in `block in upgrade'
        25: from /usr/local/bin/crew:655:in `expand_dependencies'
        24: from /usr/local/bin/crew:646:in `push_dependencies'
        23: from /usr/local/bin/crew:646:in `each'
        22: from /usr/local/bin/crew:651:in `block in push_dependencies'
        21: from /usr/local/bin/crew:646:in `push_dependencies'
        20: from /usr/local/bin/crew:646:in `each'
        19: from /usr/local/bin/crew:651:in `block in push_dependencies'
        18: from /usr/local/bin/crew:646:in `push_dependencies'
        17: from /usr/local/bin/crew:646:in `each'
        16: from /usr/local/bin/crew:651:in `block in push_dependencies'
        15: from /usr/local/bin/crew:646:in `push_dependencies'
        14: from /usr/local/bin/crew:646:in `each'
        13: from /usr/local/bin/crew:651:in `block in push_dependencies'
        12: from /usr/local/bin/crew:646:in `push_dependencies'
        11: from /usr/local/bin/crew:646:in `each'
        10: from /usr/local/bin/crew:650:in `block in push_dependencies'
         9: from /usr/local/bin/crew:143:in `search'
         8: from /usr/local/lib64/ruby/2.5.0/find.rb:43:in `find'
         7: from /usr/local/lib64/ruby/2.5.0/find.rb:43:in `each'
         6: from /usr/local/lib64/ruby/2.5.0/find.rb:48:in `block in find'
         5: from /usr/local/lib64/ruby/2.5.0/find.rb:48:in `catch'
         4: from /usr/local/lib64/ruby/2.5.0/find.rb:49:in `block (2 levels) in find'
         3: from /usr/local/bin/crew:144:in `block in search'
         2: from /usr/local/bin/crew:110:in `set_package'
         1: from /usr/local/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': /usr/local/lib/crew/packages/xkeyboard_config.rb:22: syntax error, unexpected tIDENTIFIER, expecting keyword_end (SyntaxError)
.../rules/compat/map-variants.py"i
```

## Versions and system information
```shell
chronos@localhost ~ $ crew --version
1.3.2

chronos@localhost ~ $ cat /etc/lsb-release
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=6302806
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={0C1E39B7-DAE6-4972-8004-E96F60D9342C}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={0C1E39B7-DAE6-4972-8004-E96F60D9342C}
CHROMEOS_RELEASE_BOARD=fizz-signed-mp-v12keys
CHROMEOS_RELEASE_BRANCH_NUMBER=105
CHROMEOS_RELEASE_BUILDER_PATH=fizz-release/R80-12739.105.0
CHROMEOS_RELEASE_BUILD_NUMBER=12739
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=80
CHROMEOS_RELEASE_DESCRIPTION=12739.105.0 (Official Build) stable-channel fizz 
CHROMEOS_RELEASE_KEYSET=mp-v12
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=12739.105.0
DEVICETYPE=CHROMEBOX
GOOGLE_RELEASE=12739.105.0

chronos@localhost ~ $ uname -m
x86_64
```
---

**Comment by uberhacker** [comment]
Thank you for the feedback @ramsrib.  This should be fixed in #3970.
