### ISSUE TITLE
Arduino IDE USB device directory 

### ISSUE THREAD

**Issue by Samdvich** [skycocker/chromebrew#3971]
## Description
When running version (15) installed from the Arudino IDE package, writing to dev/ttyACM isn't possible as the directory doesn't exist. ``sudo usermod -a -G dialout <username>`` is the suggested fix, but the ttyACM devices genuinely seem to not exist on chronos:

**Checking devices**
```bash
chmod: cannot access '/dev/ttyACM*': No such file or directory
chronos@localhost /dev $ ls -l /dev/ttyACM*
ls: cannot access '/dev/ttyACM*': No such file or directory
chronos@localhost /dev $ ls -l /dev/tty*
crw-rw-rw-. 1 root tty 5, 0 Mar 29 09:52 /dev/tty
```

**Commands and errors**
```shell
chronos@localhost /dev $ crew install arduino_ide
(i) arduino_ide: Arduino is an open-source physical computing platform based on a simple I/O board and a development environment that implements the Processing/Wiring language.
https://www.arduino.cc/
version 1.8.10
Package arduino_ide already installed, skipping...
Arduino_ide installed!
chronos@localhost /dev $ arduino
Enabling Arduino write access...
chmod: cannot access '/dev/ttyACM*': No such file or directory
Picked up JAVA_TOOL_OPTIONS: 
Set log4j store directory /home/chronos/user/.arduino15
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.SplashScreen.getSplashScreen(SplashScreen.java:117)
        at processing.app.Base.<init>(Base.java:238)
        at processing.app.Base.main(Base.java:150)
Disabling Arduino write access...
chmod: cannot access '/dev/ttyACM*': No such file or directory
```

## Versions and system information
chromebrew: `1.3.2`

ChromeOS: 
`CHROMEOS_ARC_ANDROID_SDK_VERSION=28
 CHROMEOS_ARC_VERSION=6302806
 CHROMEOS_AUSERVER=https://tools.google.com/service/update2
 CHROMEOS_BOARD_APPID={8396029B-FCEF-9EEC-C684-3BCB8E3E9429}
 CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
 CHROMEOS_DEVSERVER=
 CHROMEOS_RELEASE_APPID={8396029B-FCEF-9EEC-C684-3BCB8E3E9429}
 CHROMEOS_RELEASE_BOARD=reef-signed-mp-v2keys
 CHROMEOS_RELEASE_BRANCH_NUMBER=105
 CHROMEOS_RELEASE_BUILDER_PATH=reef-release/R80-12739.105.0
 CHROMEOS_RELEASE_BUILD_NUMBER=12739
 CHROMEOS_RELEASE_BUILD_TYPE=Official Build
 CHROMEOS_RELEASE_CHROME_MILESTONE=80
 CHROMEOS_RELEASE_DESCRIPTION=12739.105.0 (Official Build) stable-channel reef 
 CHROMEOS_RELEASE_KEYSET=mp-v2
 CHROMEOS_RELEASE_NAME=Chrome OS
 CHROMEOS_RELEASE_PATCH_NUMBER=0
 CHROMEOS_RELEASE_TRACK=stable-channel
 CHROMEOS_RELEASE_UNIBUILD=1
 CHROMEOS_RELEASE_VERSION=12739.105.0
 DEVICETYPE=CHROMEBOOK
 GOOGLE_RELEASE=12739.105.0`

Model: ``ASUS C213NA``

Architecture: `x86_64`

**Comment by cstrouse** [comment]
I have the option enabled in my kernel on Samsung Chromebook Plus v1.
```bash
$ sudo modprobe configs && zgrep USB_ACM /proc/config.gz
CONFIG_USB_ACM=y
$
```

Can you  plugin the device in and paste the relevant portion of your `dmesg` output?

Also, with the device plugged in, do you see the USB Modem module loaded?
```bash
$ lsmod | grep cdc_acm
```

If the module isn't being loaded properly when the device is plugged in, you may need to write a set of udev rules to handle that.

**Comment by Samdvich** [comment]
I'm currently back to working in the container, so I can't check it myself (compiler conflicts). Would I have needed to plugged in an Arduino board for it to recognise the device path?

**Comment by cstrouse** [comment]
Yes, you would need it to be plugged for the device nodes to be created. You don't need to have chromebrew installed to send the info we need to figure out how we can better support people doing microcontroller work. Once we know that it's being recognized as a USB modem we can figure out why the module isn't loading properly and/or why the device nodes aren't being created. There's not much in the existing ChromeOS udev rules so I wouldn't be surprised if we need to create our own.

**Comment by cstrouse** [comment]
Closing for inactivity.
