### ISSUE TITLE
Installer not correctly installing chromebrew on Samsung chromebook 2(peach pit)

### ISSUE THREAD

**Issue by YoshiLightStar** [skycocker/chromebrew#4127]
## Description
Provide a short description of your problem here.
Installer does not work properly and errors out, same error outputed when any install command is ran.
If you executed a specific command:
```shell
curl -Ls https://raw.github.com/skycocker/chromebrew/master/install.sh | bash
```

Output:
```Downloading gcc8...
######################################################################## 100.0%
Verifying gcc8...
gcc8-8.3.0-chromeos-armv7l.tar.xz: OK
Extracting gcc8 (this may take a while)...
Installing gcc8 (this may take a while)...
Updating version number of gcc8 in device.json...
Downloading libressl...
######################################################################## 100.0%
Verifying libressl...
libressl-3.0.2-chromeos-armv7l.tar.xz: OK
Extracting libressl (this may take a while)...
Installing libressl (this may take a while)...
Updating version number of libressl in device.json...
Downloading ruby...
######################################################################## 100.0%
Verifying ruby...
ruby-2.7.1-chromeos-armv7l.tar.xz: OK
Extracting ruby (this may take a while)...
Installing ruby (this may take a while)...
Updating version number of ruby in device.json...
Downloading libiconv...
######################################################################## 100.0%
Verifying libiconv...
libiconv-1.15-1-chromeos-armv7l.tar.xz: OK
Extracting libiconv (this may take a while)...
Installing libiconv (this may take a while)...
Updating version number of libiconv in device.json...
Downloading git...
######################################################################## 100.0%
Verifying git...
git-2.26.0-chromeos-armv7l.tar.xz: OK
Extracting git (this may take a while)...
Installing git (this may take a while)...
Updating version number of git in device.json...
Downloading libssh2...
######################################################################## 100.0%
Verifying libssh2...
libssh2-1.9.0-chromeos-armv7l.tar.xz: OK
Extracting libssh2 (this may take a while)...
Installing libssh2 (this may take a while)...
Updating version number of libssh2 in device.json...
Initialized empty Git repository in /usr/local/lib/crew/.git/
Updating origin
remote: Enumerating objects: 114, done.
remote: Counting objects: 100% (114/114), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 23879 (delta 62), reused 50 (delta 28), pack-reused 23765
Receiving objects: 100% (23879/23879), 6.38 MiB | 2.69 MiB/s, done.
Resolving deltas: 100% (16164/16164), done.
From https://github.com/skycocker/chromebrew
 * [new branch]        deps_order                       -> origin/deps_order
 * [new branch]        gh-pages                         -> origin/gh-pages
 * [new branch]        master                           -> origin/master
 * [new branch]        pr/205                           -> origin/pr/205
 * [new branch]        revert-1030-add-vpnc-package     -> origin/revert-1030-add-vpnc-package
 * [new branch]        revert-1177-update-screenfetch   -> origin/revert-1177-update-screenfetch
 * [new branch]        revert-758-add-moreutils-package -> origin/revert-758-add-moreutils-package
 * [new branch]        revert-760-add-cron-package      -> origin/revert-760-add-cron-package
 * [new branch]        revert-936-update-emacs-package  -> origin/revert-936-update-emacs-package
 * [new branch]        skiman6010-copyright-date-update -> origin/skiman6010-copyright-date-update
 * [new branch]        update-qt-packages               -> origin/update-qt-packages
 * [new tag]           0.4.1                            -> 0.4.1
 * [new tag]           v0.1                             -> v0.1
 * [new tag]           v0.1.1                           -> v0.1.1
 * [new tag]           v0.2                             -> v0.2
 * [new tag]           v0.2.1                           -> v0.2.1
 * [new tag]           v0.2.1.1                         -> v0.2.1.1
 * [new tag]           v0.2.1.2                         -> v0.2.1.2
 * [new tag]           v0.3                             -> v0.3
 * [new tag]           v0.3.1                           -> v0.3.1
 * [new tag]           v0.4                             -> v0.4
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
HEAD is now at be7cbbbc Merge pull request #4109 from uberhacker/update-brave-package
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
HEAD is now at be7cbbbc Merge pull request #4109 from uberhacker/update-brave-package
Package lists, crew, and library updated.
Generating compatible packages...
Traceback (most recent call last):
        9: from /usr/local/bin/crew:1079:in `<main>'
        8: from /usr/local/bin/crew:1052:in `update_command'
        7: from /usr/local/bin/crew:393:in `update'
        6: from /usr/local/bin/crew:181:in `generate_compatible'
        5: from /usr/local/lib/ruby/2.7.0/find.rb:43:in `find'
        4: from /usr/local/lib/ruby/2.7.0/find.rb:43:in `each'
        3: from /usr/local/lib/ruby/2.7.0/find.rb:48:in `block in find'
        2: from /usr/local/lib/ruby/2.7.0/find.rb:48:in `catch'
        1: from /usr/local/lib/ruby/2.7.0/find.rb:49:in `block (2 levels) in find'
/usr/local/bin/crew:185:in `block in generate_compatible': undefined method `include?' for nil:NilClass (NoMethodError)
```

## Versions and system information
chromebrew: `1.4.2`

ChromeOS: `12105.100.0, 75`

Model: XE503C12 (Peach pit)

Architecture: armv7l

**Comment by uberhacker** [comment]
@YoshiLightStar:  Did you install from scratch or after a Powerwash?  If not, it's possible you have files from a previous version creating a conflict.  If you don't have anything else installed there, you could avoid a Powerwash with the following:
```
$ rm -rf /usr/local

**Comment by YoshiLightStar** [comment]
Appears you were correct
