### ISSUE TITLE
crew update fails

### ISSUE THREAD

**Issue by vincowl** [skycocker/chromebrew#4203]
Running `crew update` on x86_64 sends
```shell
chronos@localhost ~/Downloads $ crew update
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
HEAD is now at f540f740 Merge pull request #4200 from uberhacker/update-cmake-package
Package lists, crew, and library updated.
Generating compatible packages...
Traceback (most recent call last):
        9: from /usr/local/bin/crew:1079:in `<main>'
        8: from /usr/local/bin/crew:1052:in `update_command'
        7: from /usr/local/bin/crew:393:in `update'
        6: from /usr/local/bin/crew:181:in `generate_compatible'
        5: from /usr/local/lib64/ruby/2.7.0/find.rb:43:in `find'
        4: from /usr/local/lib64/ruby/2.7.0/find.rb:43:in `each'
        3: from /usr/local/lib64/ruby/2.7.0/find.rb:48:in `block in find'
        2: from /usr/local/lib64/ruby/2.7.0/find.rb:48:in `catch'
        1: from /usr/local/lib64/ruby/2.7.0/find.rb:49:in `block (2 levels) in find'
/usr/local/bin/crew:185:in `block in generate_compatible': undefined method `include?' for nil:NilClass (NoMethodError)
```
Gonna investigate this

**Comment by vincowl** [comment]
Sorry, this was a mistake on my install. Problem solved
