### ISSUE TITLE
Error installing docbook_xsl   sed: can't read /usr/local/etc/xml/catalog.xml: No such file or directory

### ISSUE THREAD

**Issue by supechicken666** [skycocker/chromebrew#4319]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
This happened while I install docbook_xsl

If you executed a specific command:
```shell
crew install docbook_xsl
```

Output:
The full version is here
https://drive.google.com/file/d/1-2reSmG5-1nNFq0h9j4HCaIuQoNwmL5w/view?usp=sharing
```shell
install: creating directory '/usr/local/tmp/crew/dest/usr/local/share/doc'
install: creating directory '/usr/local/tmp/crew/dest/usr/local/share/doc/docbook-xsl-1.79.1'
'README' -> '/usr/local/tmp/crew/dest/usr/local/share/doc/docbook-xsl-1.79.1/README.txt'
'RELEASE-NOTES.html' -> '/usr/local/tmp/crew/dest/usr/local/share/doc/docbook-xsl-1.79.1/RELEASE-NOTES.html'
'RELEASE-NOTES.txt' -> '/usr/local/tmp/crew/dest/usr/local/share/doc/docbook-xsl-1.79.1/RELEASE-NOTES.txt'
'RELEASE-NOTES.xml' -> '/usr/local/tmp/crew/dest/usr/local/share/doc/docbook-xsl-1.79.1/RELEASE-NOTES.xml'
'NEWS' -> '/usr/local/tmp/crew/dest/usr/local/share/doc/docbook-xsl-1.79.1/NEWS'
'NEWS.html' -> '/usr/local/tmp/crew/dest/usr/local/share/doc/docbook-xsl-1.79.1/NEWS.html'
'NEWS.xml' -> '/usr/local/tmp/crew/dest/usr/local/share/doc/docbook-xsl-1.79.1/NEWS.xml'
sed: can't read /usr/local/etc/xml/catalog.xml: No such file or directory
docbook_xsl failed to install: `sed -i -e 's,<!-- .* -->,,g' /usr/local/etc/xml/catalog.xml` exited with 2
```

## Versions and system information
chromebrew: `crew --version`
1.4.4

Architecture: x86_64

## Addtional information
How can I get the missing xml file?

---

## That's it
Thank you for submitting your issue.
When done, please delete the parts of this template which you don't need or these, which are only for guidance.

**Comment by ThatGeekyWeeb** [comment]
This issue should be fixed by #4318

**Comment by ThatGeekyWeeb** [comment]
@supechicken666: Is `docbook_xml51` installed?

**Comment by supechicken666** [comment]
No,as the docbook_xml51 is also depends on docbook_xml
Just crew update try to reinstall docbook_xml and get an new error
```shell
chronos@localhost /usr/local/etc/xml $ crew install docbook_xml51
sh: 0: getcwd() failed: No such file or directory
docbook_xml51: Version 5.1 - document type definitions for verification of XML data files against the DocBook rule set
http://www.docbook.org
version 5.1
Precompiled binary available, downloading...
Traceback (most recent call last):
        7: from /usr/local/bin/crew:1080:in `<main>'
        6: from /usr/local/bin/crew:997:in `install_command'
        5: from /usr/local/bin/crew:997:in `each'
        4: from /usr/local/bin/crew:1001:in `block in install_command'
        3: from /usr/local/bin/crew:686:in `resolve_dependencies_and_install'
        2: from /usr/local/bin/crew:785:in `install'
        1: from /usr/local/bin/crew:495:in `download'
/usr/local/bin/crew:495:in `chdir': No such file or directory - getcwd (Errno::ENOENT)
        6: from /usr/local/bin/crew:1080:in `<main>'
        5: from /usr/local/bin/crew:997:in `install_command'
        4: from /usr/local/bin/crew:997:in `each'
        3: from /usr/local/bin/crew:1001:in `block in install_command'
        2: from /usr/local/bin/crew:692:in `resolve_dependencies_and_install'
        1: from /usr/local/bin/crew:692:in `ensure in resolve_dependencies_and_install'
/usr/local/bin/crew:692:in `chdir': No such file or directory - getcwd (Errno::ENOENT)
```

**Comment by ThatGeekyWeeb** [comment]
I'm sorry, it shouldn't be installing a binary, please install with `-s`
`crew reinstall docbook_xml51 -s && crew reinstall docbook_xml`

**Comment by supechicken666** [comment]
The same error is outputed, am my devices missing some package?

**Comment by ThatGeekyWeeb** [comment]
Something is wrong with your device/install
> ```
> sh: 0: getcwd() failed: No such file or directory
> ```

**Comment by ThatGeekyWeeb** [comment]
You seem to be in a directory that does not exist. Please `cd ~` and try again.

**Comment by supechicken666** [comment]
Same. Do I need to reinstall chrome os

**Comment by ThatGeekyWeeb** [comment]
This doesn't make any sense, you shouldn't be receiving this error. Please fresh install.
```
cd; rm /usr/local/* -rf && curl -Ls https://git.io/JU4AW | bash && crew update && crew install docbook_xml51 -s
```

**Comment by supechicken666** [comment]
Just remove all files at /usr/local and did a fresh install
But the thing seems go bad
```shell
From https://github.com/skycocker/chromebrew
 * [new branch]        deps_order                       -> origin/deps_order
 * [new branch]        gh-pages                         -> origin/gh-pages
 * [new branch]        master                           -> origin/master
 * [new branch]        pr/205                           -> origin/pr/205
 * [new branch]        revert-1030-add-vpnc-package     -> origin/revert-1030-add-vpnc-package
 * [new branch]        revert-1177-update-screenfetch   -> origin/revert-1177-update-screenfetch
 * [new branch]        revert-758-add-moreutils-package -> origin/revert-758-add-moreutils-package
 * [new branch]        revert-760-add-cron-package      -> origin/revert-760-add-cron-package
 * [new branch]        revert-936-update-emacs-package  -> origin/revert-936-update-emacs-package
 * [new branch]        skiman6010-copyright-date-update -> origin/skiman6010-copyright-date-update
 * [new branch]        update-qt-packages               -> origin/update-qt-packages
 * [new tag]           0.4.1                            -> 0.4.1
 * [new tag]           v0.1                             -> v0.1
 * [new tag]           v0.1.1                           -> v0.1.1
 * [new tag]           v0.2                             -> v0.2
 * [new tag]           v0.2.1                           -> v0.2.1
 * [new tag]           v0.2.1.1                         -> v0.2.1.1
 * [new tag]           v0.2.1.2                         -> v0.2.1.2
 * [new tag]           v0.3                             -> v0.3
 * [new tag]           v0.3.1                           -> v0.3.1
 * [new tag]           v0.4                             -> v0.4
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
HEAD is now at 5632d5e9 Update - gtk_doc (#4305)
Traceback (most recent call last):
        5: from /usr/local/bin/crew:10:in `<main>'
        4: from /usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        3: from /usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        2: from /usr/local/lib64/ruby/2.7.0/digest/sha2.rb:14:in `<top (required)>'
        1: from /usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/local/lib64/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': libssl.so.47: cannot open shared object file: No such file or directory - /usr/local/lib64/ruby/2.7.0/x86_64-linux-gnu/digest/sha2.so (LoadError)
```

**Comment by ThatGeekyWeeb** [comment]
Pardon, thats my fault, the link I gave you is to a zero issue fork, but it wasn't setup to use x86.
Please use this instead `curl -Ls git.io/vddgY | bash`

**Comment by supechicken666** [comment]
Just reinstall the system, and install the docbook_xml51 first, then install docbook_xml
The same error happened again
```shell
Rename all *.la files to *.la_tmp
sed: can't read /usr/local/etc/xml/catalog.xml: No such file or directory
docbook_xml50 failed to install: `sed -i -e 's,<!-- .* -->,,g' /usr/local/etc/xml/catalog.xml` exited with 2
```

**Comment by ThatGeekyWeeb** [comment]
Alright, perfect, thats the issue i fixed in #4318

**Comment by supechicken666** [comment]
```shell
chronos@localhost / $ system "sed -i -e 's,<!-- .* -->,,g' #{CREW_PREFIX}/etc/xml/catal
og.xml"
bash: !--: event not found
```
Happened after running the script on #4318 
Does it needs depends?

**Comment by ThatGeekyWeeb** [comment]
thats not how it works-

**Comment by supechicken666** [comment]
So what I need to do now?

**Comment by ThatGeekyWeeb** [comment]
Wait for #4318 to be merged. As it should fix everything, but I may post a quick fix for you here in a bit.

**Comment by uberhacker** [comment]
It must be a dependency issue if it fails with file not found.

**Comment by uberhacker** [comment]
Does docbook_xml51 actually install `/usr/local/etc/xml/catalog.xml`?  That might be the problem.

**Comment by ThatGeekyWeeb** [comment]
Yes, but after the changes from #4316 the HTML comment is gone, so sed fails, but only on fresh installs, #4318 fixes that.

**Comment by supechicken666** [comment]
cd to /usr/local/etc/xml/ and found a file call catalog
Just rename it by `mv catalog catalog.xml`
And the installation works
But I got an new error (Is that an fatal error?)
```shell
Building from source, this may take a while...
Rename all *.la files to *.la_tmp
xmlcatmgr: no matching entry for `-//OASIS//DTD DocBook XML V4.2//EN' of type `public'
xmlcatmgr: no matching entry for `-//OASIS//DTD DocBook XML V4.1.2//EN' of type `public'
Preconfiguring package...
Rename all *.la_tmp files back to *.la
Performing pre-install...
Performing install...
Performing post-install...
Docbook_xml installed!
```

**Comment by ThatGeekyWeeb** [comment]
@supechicken666 please 
```sh
curl -Ls "https://cdn.discordapp.com/attachments/699685435198144553/755432027032912052/ar_xml.sh" | bash && crew reinstall docbook_xml51 docbook_xml50 docbook_xml45 docbook_xml44 docbook_xml43 docbook_xml42
```
and then try to install `docbook_xsl`

**Comment by ThatGeekyWeeb** [comment]
Don't worry about `xmlcatmgr` errors they are not fatal.

**Comment by supechicken666** [comment]
> @supechicken666 please
> 
> ```shell
> curl -Ls "https://cdn.discordapp.com/attachments/699685435198144553/755432027032912052/ar_xml.sh" | bash && crew reinstall docbook_xml51 docbook_xml50 docbook_xml45 docbook_xml44 docbook_xml43 docbook_xml42
> ```
> 
> and then try to install `docbook_xsl`

What does this script works for?

**Comment by ThatGeekyWeeb** [comment]
> Does docbook_xml51 actually install `/usr/local/etc/xml/catalog.xml`? That might be the problem.

> ```
> crew whatprovides /usr/local/etc/xml/catalog.xml
> docbook_xml51: /usr/local/etc/xml/catalog.xml
> ```

**Comment by ThatGeekyWeeb** [comment]
@supechicken666: The script grabs the files from #4318 and places them in the proper dirs.

**Comment by supechicken666** [comment]
After ran `curl -Ls "https://cdn.discordapp.com/attachments/699685435198144553/755432027032912052/ar_xml.sh" | bash && crew reinstall docbook_xml51 docbook_xml50 docbook_xml45 docbook_xml44 docbook_xml43 docbook_xml42`
Try to install firefox but it gives me an error during install gtk_doc
```shell
checking for DocBook XML DTD V4.3 in XML catalog... not found
configure: error: could not find DocBook XML DTD V4.3 in XML catalog
gtk_doc failed to install: `./configure --prefix=/usr/local --libdir=/usr/local/lib64 --mandir=/usr/local/share/man --build=x86_64-cros-linux-gnu --host=x86_64-cros-linux-gnu --target=x86_64-cros-linux-gnu --with-xml-catalog=/usr/local/etc/xml/catalog.xml` exited with 1
```
Anyone know how to solve it?
Thanks

**Comment by ThatGeekyWeeb** [comment]
thats odd, install `docbook_xml43` please.

**Comment by supechicken666** [comment]
Already installed with docbook_xml

**Comment by ThatGeekyWeeb** [comment]
hmm. Thats odd, let me do some debugging,  and report back.

**Comment by ThatGeekyWeeb** [comment]
@supechicken666; can you run
```
xmlcatalog /usr/local/etc/xml/catalog.xml "-//OASIS//DTD DocBook XML V4.3//EN"
``` 
For me? It should tell me if `docbook_xml43` is installed properly or not.

**Comment by supechicken666** [comment]
Is it normal?
```shell
chronos@localhost /usr/local/etc/xml $ xmlcatalog /usr/local/etc/xml/catalog.xml "-//OASIS//DTD DocBook XML V4.3//EN"
file:///usr/local/share/xml/docbook/4.3/catalog.xml
```

**Comment by ThatGeekyWeeb** [comment]
Yes that's normal, try and install `gtk_doc` manually. `crew install gtk_doc -s`

**Comment by supechicken666** [comment]
Same
```shell
checking for XML catalog... /usr/local/etc/xml/catalog.xml
checking for xmlcatalog... /usr/local/bin/xmlcatalog
checking for DocBook XML DTD V4.3 in XML catalog... not found
configure: error: could not find DocBook XML DTD V4.3 in XML catalog
gtk_doc failed to install: `./configure --prefix=/usr/local --libdir=/usr/local/lib64 --mandir=/usr/local/share/man --build=x86_64-cros-linux-gnu --host=x86_64-cros-linux-gnu --target=x86_64-cros-linux-gnu --with-xml-catalog=/usr/local/etc/xml/catalog.xml` exited with 1
```

**Comment by ThatGeekyWeeb** [comment]
Can you `cat /usr/local/etc/xml/catalog.xml` please?

**Comment by supechicken666** [comment]
```shell
<?xml version="1.0"?>
<!DOCTYPE catalog PUBLIC "-//OASIS//DTD Entity Resolution XML Catalog V1.0//EN" "http://www.oasis-open.org/committees/entity/release/1.0/catalog.dtd">
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
  <delegatePublic publicIdStartString="-//OASIS//ENTITIES DocBook XML" catalog="file:///usr/local/etc/xml/docbook"/>
  <delegatePublic publicIdStartString="-//OASIS//DTD DocBook XML" catalog="file:///usr/local/etc/xml/docbook"/>
  <delegateSystem systemIdStartString="http://www.oasis-open.org/docbook/" catalog="file:///usr/local/etc/xml/docbook"/>
  <delegateURI uriStartString="http://www.oasis-open.org/docbook/" catalog="file:///usr/local/etc/xml/docbook"/>
</catalog>
```

**Comment by ThatGeekyWeeb** [comment]
And `cat /usr/local/etc/xml/docbook` please?

**Comment by ThatGeekyWeeb** [comment]
And, whats in `/usr/local/share/xml/docbook`?
```sh
ls /usr/local/share/xml/docbook
```

**Comment by supechicken666** [comment]
```shell
<?xml version="1.0"?>
<!DOCTYPE catalog PUBLIC "-//OASIS//DTD Entity Resolution XML Catalog V1.0//EN" "http://www.oasis-open.org/committees/entity/release/1.0/catalog.dtd">

<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
<public publicId="-//OASIS//DTD DocBook XML V5.1//EN" uri="http://www.oasis-open.org/docbook/xml/5.1/docbookx.dtd" />
<public publicId="-//OASIS//DTD DocBook XML CALS Table Model V5.1//EN" uri="file:///usr/local/share/xml/docbook/xml-dtd-5.1/calstblx.dtd" />
<public publicId="-//OASIS//DTD XML Exchange Table Model 19990315//EN" uri="file:///usr/local/share/xml/docbook/xml-dtd-5.1/soextblx.dtd" />
<public publicId="-//OASIS//ELEMENTS DocBook XML Information Pool V5.1//EN" uri="file:///usr/local/share/xml/docbook/xml-dtd-5.1/dbpoolx.mod" />
<public publicId="-//OASIS//ELEMENTS DocBook XML Document Hierarchy V5.1//EN" uri="file:///usr/local/share/xml/docbook/xml-dtd-5.1/dbhierx.mod" />
<public publicId="-//OASIS//ELEMENTS DocBook XML HTML Tables V5.1//EN" uri="file:///usr/local/share/xml/docbook/xml-dtd-5.1/htmltblx.mod" />
<public publicId="-//OASIS//ENTITIES DocBook XML Notations V5.1//EN" uri="file:///usr/local/share/xml/docbook/xml-dtd-5.1/dbnotnx.mod" />
<public publicId="-//OASIS//ENTITIES DocBook XML Character Entities V5.1//EN" uri="file:///usr/local/share/xml/docbook/xml-dtd-5.1/dbcentx.mod" />
<public publicId="-//OASIS//ENTITIES DocBook XML Additional General Entities V5.1//EN" uri="file:///usr/local/share/xml/docbook/xml-dtd-5.1/dbgenent.mod" />
<rewriteSystem systemIdStartString="http://www.oasis-open.org/docbook/xml/5.1" rewritePrefix="file:///usr/local/share/xml/docbook/xml-dtd-5.1" />
<rewriteURI uriStartString="http://www.oasis-open.org/docbook/xml/5.1" rewritePrefix="file:///usr/local/share/xml/docbook/xml-dtd-5.1" />
<public publicId="-//OASIS//DTD DocBook XML V5.0//EN" uri="/usr/local/share/xml/docbook/5.0/catalog.xml" />
<public publicId="-//OASIS//DTD DocBook XML V4.5//EN" uri="/usr/local/share/xml/docbook/4.5/catalog.xml" />
<public publicId="-//OASIS//DTD DocBook XML V4.4//EN" uri="/usr/local/share/xml/docbook/4.4/catalog.xml" />
<public publicId="-//OASIS//DTD DocBook XML V4.3//EN" uri="/usr/local/share/xml/docbook/4.3/catalog.xml" />
<public publicId="-//OASIS//DTD DocBook XML V4.2//EN" uri="/usr/local/share/xml/docbook/4.2/catalog.xml" />
<public publicId="-//OASIS//DTD DocBook XML V4.1.2//EN" uri="/usr/local/share/xml/docbook/4.2/catalog.xml" />
</catalog>
```

**Comment by supechicken666** [comment]
```shell
chronos@localhost /usr/local/etc/xml $ ls /usr/local/share/xml/docbook
4.2  4.3  4.4  4.5  5.0  xml-dtd-5.1
```

**Comment by ThatGeekyWeeb** [comment]
Hmmmm, that's weird.
