### ISSUE TITLE
crew errors when no search results

### ISSUE THREAD

**Issue by cstrouse** [skycocker/chromebrew#4596]
```
chronos@localhost /usr/local/tmp/v-0.1.29 $ crew search kerberos
Traceback (most recent call last):
        10: from /usr/local/bin/crew:1089:in `<main>'
         9: from /usr/local/bin/crew:1054:in `search_command'
         8: from /usr/local/bin/crew:1054:in `each'
         7: from /usr/local/bin/crew:1055:in `block in search_command'
         6: from /usr/local/bin/crew:210:in `regexp_search'
         5: from /usr/local/lib64/ruby/2.7.0/find.rb:43:in `find'
         4: from /usr/local/lib64/ruby/2.7.0/find.rb:43:in `each'
         3: from /usr/local/lib64/ruby/2.7.0/find.rb:48:in `block in find'
         2: from /usr/local/lib64/ruby/2.7.0/find.rb:48:in `catch'
         1: from /usr/local/lib64/ruby/2.7.0/find.rb:49:in `block (2 levels) in find'
/usr/local/bin/crew:214:in `block in regexp_search': undefined method `description' for nil:NilClass (NoMethodError)
```

**Comment by uberhacker** [comment]
Try adding a description to `dotnet.rb`.

**Comment by cstrouse** [comment]
Yep, that was it. Search should probably be tolerant of an empty string description though don't you think?

**Comment by uberhacker** [comment]
I agree in part, however, all packages should have a description, don't you think? ;)
