### ISSUE TITLE
gcc10 compile issue

### ISSUE THREAD

**Issue by satmandu** [skycocker/chromebrew#4684]
I've tried to recompile gcc10 (gcc 10.2) with ```system "./contrib/download_prerequisites"``` to make sure I don't have any isl issues. gcc10 seems to compile fine, but I'm getting this weird issue when running gcc (presumably with lot?) and trying to compile evolution_data_server, which seems to indicate a failure to link libzstd properly when compiling gcc.

(Yes libzstd is there in /usr/local/lib64. )

Any ideas on what to change here?

I've tried to recompile libzstd with -pthread since there are reports that might be an issue, but no change.

```
FAILED: src/camel/Camel-1.2.gir 
cd /usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel && /usr/local/bin/cmake -E env "CC='/usr/local/bin/cc'" LDFLAGS= LD_LIBRARY_PATH=\"/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build:/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src:/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel:/usr/local/lib:/usr/local/lib64\" /usr/local/bin/g-ir-scanner --add-include-path=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build --add-include-path=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src --add-include-path=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38 --add-include-path=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/src --add-include-path=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel --add-include-path=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/src/camel --library-path=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build --library-path=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src --library-path=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel --identifier-prefix=Camel --identifier-prefix=camel --add-include-path=/usr/local/share/gir-1.0 --library-path=/usr/local/lib --pkg-export camel-1.2 --c-include=camel/camel.h --cflags-begin -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/src/camel -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38 -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/src -DCAMEL_COMPILATION --cflags-end --verbose --namespace=Camel --nsversion=1.2 --no-libtool --library=camel-1.2 --include=GObject-2.0 --include=Gio-2.0 --include=libxml2-2.0 --warn-all -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/src/camel -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38 -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/src -DCAMEL_COMPILATION --filelist=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel/Camel_1_2_gir_files --output /usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel/Camel-1.2.gir --accept-unprefixed
/usr/local/bin/cc -E -DCAMEL_COMPILATION -I. -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/src/camel -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38 -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/src -I/usr/local/include/gio-unix-2.0 -I/usr/local/include/libxml2 -I/usr/local/include/libmount -I/usr/local/include/blkid -I/usr/local/lib64/libffi-3.2.1/include -I/usr/local/include/glib-2.0 -I/usr/local/lib64/glib-2.0/include -o g-ir-cpp-idg2u5hu.i -C /usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel/g-ir-cpp-idg2u5hu.c
/usr/local/libexec/gcc/x86_64-cros-linux-gnu/10.2.0/cc1: error while loading shared libraries: libzstd.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/distutils/unixccompiler.py", line 107, in preprocess
    self.spawn(pp_args)
  File "/usr/local/lib/python3.9/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/local/lib/python3.9/distutils/spawn.py", line 87, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/usr/local/bin/cc' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/g-ir-scanner", line 99, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/usr/local/lib64/gobject-introspection/giscanner/scannermain.py", line 590, in scanner_main
    ss, filenames = create_source_scanner(options, args)
  File "/usr/local/lib64/gobject-introspection/giscanner/scannermain.py", line 463, in create_source_scanner
    ss.parse_files(filenames)
  File "/usr/local/lib64/gobject-introspection/giscanner/sourcescanner.py", line 262, in parse_files
    self._parse(headers)
  File "/usr/local/lib64/gobject-introspection/giscanner/sourcescanner.py", line 308, in _parse
    cc.preprocess(tmp_name_cpp,
  File "/usr/local/lib64/gobject-introspection/giscanner/ccompiler.py", line 274, in preprocess
    self.compiler.preprocess(source=source,
  File "/usr/local/lib/python3.9/distutils/unixccompiler.py", line 109, in preprocess
    raise CompileError(msg)
distutils.errors.CompileError: command '/usr/local/bin/cc' failed with exit code 1
```

This is the evolution_data_server.rb I am trying to compile, which gives me the error above at [254/938]
```
# Adapted from Arch Linux evolution-data-server PKGBUILD at:
# https://github.com/archlinux/svntogit-packages/raw/packages/evolution-data-server/trunk/PKGBUILD

require 'package'

class Evolution_data_server < Package
  description 'Centralized access to appointments and contacts'
  version '3.38.2'
  compatibility 'all'
  source_url 'https://gitlab.gnome.org/GNOME/evolution-data-server/-/archive/gnome-3-38/evolution-data-server-gnome-3-38.tar.bz2'
  source_sha256 '30f0ffa0b7779615c782b1d8d21d3fb74083cca0b2b1cf42c340be3c011fbdee'

  #depends_on 'gnome_online_accounts'
  depends_on 'nss'
  #depends_on 'krb5'
  #depends_on 'libgweather'
  #depends_on 'libical'
  #depends_on 'db'
  #depends_on 'libgdata'
  #depends_on 'libphonenumber'
  #depends_on 'intltool' => ':build'
  #depends_on 'gperf' => ':build'
  #depends_on 'gobject_introspection' => ':build'
  #depends_on 'vala' => ':build'
  #depends_on 'gtk_doc' => ':build'
  #depends_on 'boost' => ':build'
  #depends_on 'git' => ':build'
  #depends_on 'cmake' => ':build'
  #depends_on 'ninja' => ':build'
  depends_on 'nspr'
  depends_on 'libsoup'
  depends_on 'gcr'
  #depends_on 'libcanberra'
  depends_on 'libical'


  ENV['LDLAGS'] = '-fno-lto'
  def self.build
    Dir.mkdir 'build'
      Dir.chdir 'build' do
  system "cmake #{CREW_CMAKE_OPTIONS} .. -G Ninja \
  -DENABLE_INTROSPECTION=ON \
  -DENABLE_VALA_BINDINGS=OFF \
  -DENABLE_GTK_DOC=OFF \
  -DWITH_PHONENUMBER=OFF \
  -DWITH_NSPR_INCLUDES=#{CREW_PREFIX}/include/nspr \
  -DWITH_NSS_INCLUDES=#{CREW_PREFIX}/include/nss \
  -DENABLE_OAUTH2=OFF \
  -DENABLE_GOA=OFF \
  -DENABLE_WEATHER=OFF \
  -DENABLE_GOOGLE=OFF \
  -DENABLE_EXAMPLES=OFF \
  -DENABLE_CANBERRA=OFF \
  -DCMAKE_VERBOSE_MAKEFILE=ON"
  end
  system "ninja -v -C build"
  end
  def self.install
  system "DESTDIR=#{CREW_DEST_DIR} ninja -C build install"
  end
end
```

**Comment by uberhacker** [comment]
No idea.  You will just have to try different options to figure out what works.

**Comment by satmandu** [comment]
Weirdly, I had to set ```ENV['LD_LIBRARY_PATH'] = "#{CREW_LIB_PREFIX}:$LD_LIBRARY_PATH"``` to make the compilation work.

**Comment by satmandu** [comment]
This is my working gcc10 build from the gcc 10 gcc tree, which builds on x86_64,i686, and armv7l.

```
require 'package'

class Gcc10 < Package
  description 'The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Ada, and Go.'
  homepage 'https://www.gnu.org/software/gcc/'
  version '10.2.1-07fe'
  compatibility 'all'
  source_url 'https://github.com/gcc-mirror/gcc/archive/07fed10b19e1d88ad111fd27b4181e53d1aa6778.zip'
  source_sha256 '455b11e3e82118d8b026cb1a8cb0e7b8331f1f9d76551c60e6792d488b4f1f12'

  binary_url ({
     aarch64: 'file:///usr/local/tmp/packages/gcc10-10.2.1-07fe-chromeos-armv7l.tar.xz',
      armv7l: 'file:///usr/local/tmp/packages/gcc10-10.2.1-07fe-chromeos-armv7l.tar.xz',
        i686: 'file:///usr/local/tmp/packages/gcc10-10.2.1-07fe-chromeos-i686.tar.xz',
      x86_64: 'file:///usr/local/tmp/packages/gcc10-10.2.1-07fe-chromeos-x86_64.tar.xz',
  })
  binary_sha256 ({
     aarch64: 'e5405c03363f2e1feff695da2c29320665698b41877bfc32bdb670b330d7099b',
      armv7l: 'e5405c03363f2e1feff695da2c29320665698b41877bfc32bdb670b330d7099b',
        i686: '8562773de8265d440a6b4de987676959dfd5c46a7153bb0c1cb24776ba500c03',
      x86_64: '40fe0391e7cb070e1f3fe7d140dcefdcb64cd6f3063784ae93aa309cce479bc4',
  })




  depends_on 'unzip' => :build
  depends_on 'gawk' => :build
  depends_on 'dejagnu' => :build # for test
  depends_on 'icu4c' => :build
  depends_on 'python27' => :build
  depends_on 'python3' => :build

  depends_on 'binutils'
  depends_on 'gmp'
  depends_on 'mpfr'
  depends_on 'mpc'
  depends_on 'isl'
  depends_on 'glibc'
  depends_on 'zstd'

  
  
  def self.preinstall
    installed_gccver = `gcc -v 2>&1 | tail -1 | cut -d' ' -f3`.chomp
    gcc_version = version.split("-")[0]
    abort "GCC version #{installed_gccver} already installed.".lightgreen unless "#{installed_gccver}" == "No" || "#{installed_gccver}" == "not" || "#{installed_gccver}" == "gcc:" || "#{installed_gccver}" == "#{gcc_version}"
  end

  def self.build
    gcc_version = version.split("-")[0]
    
    # previous compile issue
    # /usr/local/bin/ld: cannot find crti.o: No such file or directory
    # /usr/local/bin/ld: cannot find /usr/lib64/libc_nonshared.a
    ENV["LIBRARY_PATH"] = "#{CREW_LIB_PREFIX}"   # fix x86_64 issues
    system "mkdir -p objdir"
    system "mkdir -p objdir/gcc/.deps"
    # This fixes a PATH_MAX undefined error which breaks libsanitizer
    # "libsanitizer/asan/asan_linux.cpp:217:21: error: ‘PATH_MAX’ was not declared in this scope"
    # This is defined in https://chromium.googlesource.com/chromiumos/third_party/kernel/+/refs/heads/chromeos-5.4/include/uapi/linux/limits.h
    # and is defined as per suggested method here: https://github.com/ZefengWang/cross-tool-chain-build
    # The following is due to sed not passing newlines right.
    system "grep  -q 4096 libsanitizer/asan/asan_linux.cpp || (sed -i '77a #endif' libsanitizer/asan/asan_linux.cpp &&
    sed -i '77a #define PATH_MAX 4096' libsanitizer/asan/asan_linux.cpp &&
    sed -i '77a #ifndef PATH_MAX' libsanitizer/asan/asan_linux.cpp)"
    Dir.chdir("objdir") do
      case ARCH
      when 'armv7l', 'armv8l', 'aarch64'
        system "../configure",
        "--prefix=#{CREW_PREFIX}",
        "--libdir=#{CREW_LIB_PREFIX}",
        "--build=armv7l-cros-linux-gnueabihf",
        "--host=armv7l-cros-linux-gnueabihf",
        "--target=armv7l-cros-linux-gnueabihf",
        "--enable-checking=release",
        "--disable-multilib",
        "--enable-lto",
        "--enable-threads=posix",
        "--disable-bootstrap",
        "--disable-werror",
        "--disable-libmpx",
        "--enable-static",
        "--enable-shared",
        "--program-suffix=-#{gcc_version}",
        "--with-arch=armv7-a",
        "--with-tune=cortex-a15",
        "--with-fpu=neon",
        "--with-float=hard"
      when 'x86_64'
        system "../configure",
        "--prefix=#{CREW_PREFIX}",
        "--libdir=#{CREW_LIB_PREFIX}",
        "--build=#{ARCH}-cros-linux-gnu",
        "--host=#{ARCH}-cros-linux-gnu",
        "--target=#{ARCH}-cros-linux-gnu",
        "--enable-checking=release",
        "--enable-lto",
        "--disable-multilib",
        "--enable-threads=posix",
        "--disable-bootstrap",
        "--disable-werror",
        "--disable-libmpx",
        "--enable-static",
        "--enable-shared",
        "--program-suffix=-#{gcc_version}",
        "--with-arch-64=x86-64"
      when 'i686'
        system "../configure",
        "--prefix=#{CREW_PREFIX}",
        "--libdir=#{CREW_LIB_PREFIX}",
        "--build=#{ARCH}-cros-linux-gnu",
        "--host=#{ARCH}-cros-linux-gnu",
        "--target=#{ARCH}-cros-linux-gnu",
        "--enable-checking=release",
        "--enable-lto",
        "--disable-multilib",
        "--enable-threads=posix",
        "--disable-bootstrap",
        "--disable-werror",
        "--disable-libmpx",
        "--enable-static",
        "--enable-shared",
        "--program-suffix=-#{gcc_version}",
        "--with-arch-32=i686"
      end
      system 'make'
    end
  end

  # preserve for check, skip check for current version
  def self.check
    Dir.chdir("objdir") do
      #system "make -k check -j#{CREW_NPROC}"
      #system "../contrib/test_summary"
    end
  end

  def self.install
    Dir.chdir("objdir") do
      system "make", "DESTDIR=#{CREW_DEST_DIR}", "install-strip"

      gcc_arch = `gcc/xgcc -dumpmachine`.chomp
      gcc_version = version.split("-")[0]
      #gcc_version = `cat ../gcc/BASE-VER`
      #gcc_version = `gcc/xgcc -dumpversion`.chomp
      gcc_dir = "gcc/#{gcc_arch}/#{gcc_version}"
      gcc_libdir = "#{CREW_LIB_PREFIX}/#{gcc_dir}"

      # http://www.linuxfromscratch.org/lfs/view/development/chapter06/gcc.html#contents-gcc
      # move a misplaced file
      # The installation stage puts some files used by gdb under the /usr/local/lib(64) directory. This generates spurious error messages when performing ldconfig. This command moves the files to another location.
      system "mkdir -pv #{CREW_DEST_PREFIX}/share/gdb/auto-load/usr/lib"
      system "mv -v #{CREW_DEST_LIB_PREFIX}/*gdb.py #{CREW_DEST_PREFIX}/share/gdb/auto-load/usr/lib"

      # Install Binary File Descriptor library (BFD)
      system "install -v -dm755 #{CREW_DEST_LIB_PREFIX}/bfd-plugins"

      # Add a compatibility symlink to enable building programs with Link Time Optimization (LTO)
      system "ln -rsfv #{CREW_DEST_PREFIX}/libexec/#{gcc_dir}/liblto_plugin.so #{CREW_DEST_LIB_PREFIX}/bfd-plugins/"

      # Make symbolic links
      Dir.chdir "#{CREW_DEST_LIB_PREFIX}/#{gcc_dir}" do
        system "find . -type f -maxdepth 1 -exec ln -sv #{gcc_libdir}/{} #{CREW_DEST_LIB_PREFIX}/{} \\;"
      end

      system "ln -rsv #{CREW_DEST_PREFIX}/bin/gcc-#{gcc_version} #{CREW_DEST_PREFIX}/bin/cc"
      system "ln -rsv #{CREW_DEST_PREFIX}/bin/gcc-#{gcc_version} #{CREW_DEST_PREFIX}/bin/gcc"
      system "ln -rsv #{CREW_DEST_PREFIX}/bin/c++-#{gcc_version} #{CREW_DEST_PREFIX}/bin/c++"
      system "ln -rsv #{CREW_DEST_PREFIX}/bin/g++-#{gcc_version} #{CREW_DEST_PREFIX}/bin/g++"
      system "ln -rsv #{CREW_DEST_PREFIX}/bin/cpp-#{gcc_version} #{CREW_DEST_PREFIX}/bin/cpp"
      system "ln -rsv #{CREW_DEST_PREFIX}/bin/gcc-ar-#{gcc_version} #{CREW_DEST_PREFIX}/bin/gcc-ar"
      system "ln -rsv #{CREW_DEST_PREFIX}/bin/gcc-nm-#{gcc_version} #{CREW_DEST_PREFIX}/bin/gcc-nm"
      system "ln -rsv #{CREW_DEST_PREFIX}/bin/gcc-ranlib-#{gcc_version} #{CREW_DEST_PREFIX}/bin/gcc-ranlib"
      system "ln -rsv #{CREW_DEST_PREFIX}/bin/gcov-#{gcc_version} #{CREW_DEST_PREFIX}/bin/gcov"
      system "ln -rsv #{CREW_DEST_PREFIX}/bin/gcov-dump-#{gcc_version} #{CREW_DEST_PREFIX}/bin/gcov-dump"
      system "ln -rsv #{CREW_DEST_PREFIX}/bin/gcov-tool-#{gcc_version} #{CREW_DEST_PREFIX}/bin/gcov-tool"
      system "ln -rsv #{CREW_DEST_PREFIX}/bin/gfortran-#{gcc_version} #{CREW_DEST_PREFIX}/bin/gfortran"

      system "ln -rsv #{CREW_DEST_PREFIX}/bin/#{gcc_arch}-c++-#{gcc_version} #{CREW_DEST_PREFIX}/bin/#{gcc_arch}-c++"
      system "ln -rsv #{CREW_DEST_PREFIX}/bin/#{gcc_arch}-g++-#{gcc_version} #{CREW_DEST_PREFIX}/bin/#{gcc_arch}-g++"
      system "ln -rsv #{CREW_DEST_PREFIX}/bin/#{gcc_arch}-gcc-#{gcc_version} #{CREW_DEST_PREFIX}/bin/#{gcc_arch}-gcc"
      system "ln -rsv #{CREW_DEST_PREFIX}/bin/#{gcc_arch}-gcc-ar-#{gcc_version} #{CREW_DEST_PREFIX}/bin/#{gcc_arch}-gcc-ar"
      system "ln -rsv #{CREW_DEST_PREFIX}/bin/#{gcc_arch}-gcc-nm-#{gcc_version} #{CREW_DEST_PREFIX}/bin/#{gcc_arch}-gcc-nm"
      system "ln -rsv #{CREW_DEST_PREFIX}/bin/#{gcc_arch}-gcc-ranlib-#{gcc_version} #{CREW_DEST_PREFIX}/bin/#{gcc_arch}-gcc-ranlib"
      system "ln -rsv #{CREW_DEST_PREFIX}/bin/#{gcc_arch}-gfortran-#{gcc_version} #{CREW_DEST_PREFIX}/bin/#{gcc_arch}-gfortran"

      system "ln -rsv #{CREW_DEST_PREFIX}/share/man/man1/cpp-#{gcc_version}.1.gz #{CREW_DEST_PREFIX}/share/man/man1/cpp.1.gz"
      system "ln -rsv #{CREW_DEST_PREFIX}/share/man/man1/g++-#{gcc_version}.1.gz #{CREW_DEST_PREFIX}/share/man/man1/g++.1.gz"
      system "ln -rsv #{CREW_DEST_PREFIX}/share/man/man1/gcc-#{gcc_version}.1.gz #{CREW_DEST_PREFIX}/share/man/man1/gcc.1.gz"
      system "ln -rsv #{CREW_DEST_PREFIX}/share/man/man1/gcov-#{gcc_version}.1.gz #{CREW_DEST_PREFIX}/share/man/man1/gcov.1.gz"
      system "ln -rsv #{CREW_DEST_PREFIX}/share/man/man1/gcov-dump-#{gcc_version}.1.gz #{CREW_DEST_PREFIX}/share/man/man1/gcov-dump.1.gz"
      system "ln -rsv #{CREW_DEST_PREFIX}/share/man/man1/gcov-tool-#{gcc_version}.1.gz #{CREW_DEST_PREFIX}/share/man/man1/gcov-tool.1.gz"
      system "ln -rsv #{CREW_DEST_PREFIX}/share/man/man1/gfortran-#{gcc_version}.1.gz #{CREW_DEST_PREFIX}/share/man/man1/gfortran.1.gz"
    end
  end
end
```
