### ISSUE TITLE
[gsettings_desktop_schemas] Failed to build

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#4701]
```
[2/4] Generating GDesktopEnums-3.0.gir with a custom command
FAILED: headers/GDesktopEnums-3.0.gir 
/usr/local/bin/g-ir-scanner --no-libtool --namespace=GDesktopEnums --nsversion=3.0 --warn-all --output headers/GDesktopEnums-3.0.gir --header-only -I/usr/local/tmp/crew/3.38.0.tar.gz.dir/gsettings-desktop-schemas-3.38.0/headers -I/usr/local/tmp/crew/3.38.0.tar.gz.dir/gsettings-desktop-schemas-3.38.0/builddir/headers --filelist=/usr/local/tmp/crew/3.38.0.tar.gz.dir/gsettings-desktop-schemas-3.38.0/builddir/headers/libnoinst.so.p/GDesktopEnums_3.0_gir_filelist --identifier-prefix=GDesktop --cflags-begin -I/usr/local/include/gobject-introspection-1.0 -I/usr/local/lib64/libffi-3.2.1/include -I/usr/local/include/glib-2.0 -I/usr/local/lib64/glib-2.0/include --cflags-end --add-include-path=/usr/local/share/gir-1.0 --library noinst -L/usr/local/tmp/crew/3.38.0.tar.gz.dir/gsettings-desktop-schemas-3.38.0/builddir/headers -lgirepository-1.0 -lgobject-2.0 -lglib-2.0
Traceback (most recent call last):
  File "/usr/local/bin/g-ir-scanner", line 98, in <module>
    from giscanner.scannermain import scanner_main
  File "/usr/local/lib64/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/usr/local/lib64/gobject-introspection/giscanner/ast.py", line 29, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/usr/local/lib64/gobject-introspection/giscanner/sourcescanner.py", line 35, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ModuleNotFoundError: No module named 'giscanner._giscanner'
[3/4] Generating org.gnome.desktop.enums.xml with a custom command (wrapped by meson to capture output)
ninja: build stopped: subcommand failed.
gsettings_desktop_schemas failed to build: `ninja -C builddir` exited with 1
```

**Comment by satmandu** [comment]
A lot of your builds seem to be having issues with gobject-introspection. Can you try ```crew reinstall -s gobject_introspection```?

(This is probably a python issue too.)

**Comment by satmandu** [comment]
Actually, after updating python, could we bump gobject_introspection just to do a recompile? That might fix these issues.
