### ISSUE TITLE
[gspell] Failed to build

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#4703]
```
/usr/local/include/glib-2.0/glib/gatomic.h:112:38: note: expanded from macro 'g_atomic_pointer_get'
    __atomic_load (gapg_temp_atomic, &gapg_temp_newval, __ATOMIC_SEQ_CST); \
                                     ^~~~~~~~~~~~~~~~~
1 warning generated.
  GEN      gspell-1.deps
  CCLD     libgspell-core.la
  CCLD     libgspell-1.la
  GISCAN   Gspell-1.gir
Traceback (most recent call last):
  File "/usr/local/bin/g-ir-scanner", line 98, in <module>
    from giscanner.scannermain import scanner_main
  File "/usr/local/lib64/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/usr/local/lib64/gobject-introspection/giscanner/ast.py", line 29, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/usr/local/lib64/gobject-introspection/giscanner/sourcescanner.py", line 35, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ModuleNotFoundError: No module named 'giscanner._giscanner'
make[4]: *** [/usr/local/share/gobject-introspection-1.0/Makefile.introspection:156: Gspell-1.gir] Error 1
make[4]: Leaving directory '/usr/local/tmp/crew/gspell-1.9.1.tar.xz.dir/gspell-1.9.1/gspell'
make[3]: *** [Makefile:1192: all-recursive] Error 1
make[3]: Leaving directory '/usr/local/tmp/crew/gspell-1.9.1.tar.xz.dir/gspell-1.9.1/gspell'
make[2]: *** [Makefile:761: all] Error 2
make[2]: Leaving directory '/usr/local/tmp/crew/gspell-1.9.1.tar.xz.dir/gspell-1.9.1/gspell'
make[1]: *** [Makefile:594: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/gspell-1.9.1.tar.xz.dir/gspell-1.9.1'
make: *** [Makefile:502: all] Error 2
gspell failed to build: `make V=0 -j2` exited with 2
```

**Comment by satmandu** [comment]
Another gobject introspection issue...

**Comment by satmandu** [comment]
gspell compiled successfully for me on the x86_64 nocturne M86 docker image. (I had to install gnupg before I could compile the enchant dependency).
