### ISSUE TITLE
[libsecret] Failed to build

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#4704]
```
FAILED: libsecret/MockService-0.gir 
/usr/local/bin/g-ir-scanner --no-libtool --namespace=MockService --nsversion=0 --warn-all --output libsecret/MockService-0.gir --c-include=libsecret/mock-service.h -I/usr/local/tmp/crew/0.20.4.tar.gz.dir/libsecret-0.20.4/libsecret -I/usr/local/tmp/crew/0.20.4.tar.gz.dir/libsecret-0.20.4/build/libsecret -I./. -I../. --filelist=/usr/local/tmp/crew/0.20.4.tar.gz.dir/libsecret-0.20.4/build/libsecret/libmock-service.so.p/MockService_0_gir_filelist --include=GObject-2.0 --include=Gio-2.0 --pkg-export=mock-service-0 --cflags-begin -I./. -I../. -I/usr/local/include/glib-2.0 -I/usr/local/lib64/glib-2.0/include -I/usr/local/include/libmount -I/usr/local/include/blkid -I/usr/local/lib64/libffi-3.2.1/include -I/usr/local/include/gio-unix-2.0 -I/usr/local/include/gobject-introspection-1.0 --cflags-end --add-include-path=/usr/local/share/gir-1.0 --library mock-service -L/usr/local/tmp/crew/0.20.4.tar.gz.dir/libsecret-0.20.4/build/libsecret -lglib-2.0 -lgio-2.0 -lgobject-2.0 -lgirepository-1.0
Traceback (most recent call last):
  File "/usr/local/bin/g-ir-scanner", line 98, in <module>
    from giscanner.scannermain import scanner_main
  File "/usr/local/lib64/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/usr/local/lib64/gobject-introspection/giscanner/ast.py", line 29, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/usr/local/lib64/gobject-introspection/giscanner/sourcescanner.py", line 35, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ModuleNotFoundError: No module named 'giscanner._giscanner'
[36/72] cc -Ilibsecret/libsecret-1.so.0.0.0.p -Ilibsecret -I../libsecret -I. -I.. -I/usr/local/include/glib-2.0 -I/usr/local/lib64/glib-2.0/include -I/usr/local/include/libmount -I/usr/local/include/blkid -I/usr/local/lib64/libffi-3.2.1/include -I/usr/local/include/gio-unix-2.0 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -fcommon -fPIC -pthread -DSECRET_COMPILATION -MD -MQ libsecret/libsecret-1.so.0.0.0.p/secret-file-item.c.o -MF libsecret/libsecret-1.so.0.0.0.p/secret-file-item.c.o.d -o libsecret/libsecret-1.so.0.0.0.p/secret-file-item.c.o -c ../libsecret/secret-file-item.c
[37/72] cc -Ilibsecret/libsecret-1.so.0.0.0.p -Ilibsecret -I../libsecret -I. -I.. -I/usr/local/include/glib-2.0 -I/usr/local/lib64/glib-2.0/include -I/usr/local/include/libmount -I/usr/local/include/blkid -I/usr/local/lib64/libffi-3.2.1/include -I/usr/local/include/gio-unix-2.0 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -fcommon -fPIC -pthread -DSECRET_COMPILATION -MD -MQ libsecret/libsecret-1.so.0.0.0.p/secret-file-collection.c.o -MF libsecret/libsecret-1.so.0.0.0.p/secret-file-collection.c.o.d -o libsecret/libsecret-1.so.0.0.0.p/secret-file-collection.c.o -c ../libsecret/secret-file-collection.c
ninja: build stopped: subcommand failed.
libsecret failed to build: `ninja -v -C build` exited with 1
```

**Comment by satmandu** [comment]
Another gobject_introspection issue.
