### ISSUE TITLE
Cannot install chromebrew from scratch

### ISSUE THREAD

**Issue by vincowl** [skycocker/chromebrew#5068]
Running `curl -Ls git.io/vddgY | bash` produces on x86_64 
``` shell
HEAD is now at 9ad444e1 rebuild w/o libressl (#5066)
Package lists, crew, and library updated.
Generating compatible packages...
<internal:/usr/local/lib64/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': /usr/local/lib/crew/packages/libarchive.rb:6: syntax error, unexpected string literal, expecting `end' (SyntaxError)
  @_ver '3.5.1'
        ^
        from <internal:/usr/local/lib64/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/bin/crew:134:in `set_package'
        from /usr/local/bin/crew:200:in `block in generate_compatible'
        from /usr/local/lib64/ruby/3.0.0/find.rb:49:in `block (2 levels) in find'
        from /usr/local/lib64/ruby/3.0.0/find.rb:48:in `catch'
        from /usr/local/lib64/ruby/3.0.0/find.rb:48:in `block in find'
        from /usr/local/lib64/ruby/3.0.0/find.rb:43:in `each'
        from /usr/local/lib64/ruby/3.0.0/find.rb:43:in `find'
        from /usr/local/bin/crew:197:in `generate_compatible'
        from /usr/local/bin/crew:414:in `update'
        from /usr/local/bin/crew:1060:in `update_command'
        from /usr/local/bin/crew:1088:in `<main>'
```

**Comment by supechicken** [comment]
Fixed in #5067
