### ISSUE TITLE
crew update: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by supechicken** [skycocker/chromebrew#5319]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
`crew update` show `Segmentation fault (core dumped)` (may affect clean install)
Tried `rm -rf /usr/local/lib/crew/packages/*`

If you executed a specific command:
```shell
crew update
```

Output:
```shell
chronos@localhost /usr/local/sway-1.5.1 $ crew update
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
HEAD is now at e96e519c modemmanager -> 1.16.2 (#5318)
Package lists, crew, and library updated.
Generating compatible packages...
Segmentation fault (core dumped)   # it stuck here
```

## Versions and system information
ChromeOS: `cat /etc/lsb-release`
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7069196
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={95EE134E-B47F-43FB-9835-32C276865F9A}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={95EE134E-B47F-43FB-9835-32C276865F9A}
CHROMEOS_RELEASE_BOARD=hatch-signed-mp-v6keys
CHROMEOS_RELEASE_BRANCH_NUMBER=111
CHROMEOS_RELEASE_BUILDER_PATH=hatch-release/R87-13505.111.0
CHROMEOS_RELEASE_BUILD_NUMBER=13505
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=87
CHROMEOS_RELEASE_DESCRIPTION=13505.111.0 (Official Build) stable-channel hatch 
CHROMEOS_RELEASE_KEYSET=mp-v6
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13505.111.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13505.111.0

## Addtional information
The following appeared when I force stop the update process (seems there has a problem with `torbrowser` package):
```
^C/usr/local/lib/crew/packages/torbrowser.rb:13:in ``': Interrupt
        from /usr/local/lib/crew/packages/torbrowser.rb:13:in `<class:Torbrowser>'
        from /usr/local/lib/crew/packages/torbrowser.rb:3:in `<top (required)>'
        from <internal:/usr/local/lib64/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib64/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/bin/crew:134:in `set_package'
        from /usr/local/bin/crew:200:in `block in generate_compatible'
        from /usr/local/lib64/ruby/3.0.0/find.rb:49:in `block (2 levels) in find'
        from /usr/local/lib64/ruby/3.0.0/find.rb:48:in `catch'
        from /usr/local/lib64/ruby/3.0.0/find.rb:48:in `block in find'
        from /usr/local/lib64/ruby/3.0.0/find.rb:43:in `each'
        from /usr/local/lib64/ruby/3.0.0/find.rb:43:in `find'
        from /usr/local/bin/crew:197:in `generate_compatible'
        from /usr/local/bin/crew:414:in `update'
        from /usr/local/bin/crew:1064:in `update_command'
        from /usr/local/bin/crew:1092:in `<main>'
```

**Comment by supechicken** [comment]
Fixed by reinstall `libiconv`
