### ISSUE TITLE
[codium] Unable to install

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#5747]
```
$ crew install codium
codium: VSCodium is Open Source Software Binaries of VSCode with a community-driven default configuration.
https://vscodium.com/
Version: 1.55.2
License: MIT
require 'package'
The following packages also need to be installed: 
firefox nss 
Do you agree? [Y/n] 
Proceeding...
firefox: Mozilla Firefox (or simply Firefox) is a free and open-source web browser
/usr/local/lib/ruby/3.0.0/uri/rfc3986_parser.rb:18:in `rescue in split': bad URI(is not URI?): nil (URI::InvalidURIError)
        from /usr/local/lib/ruby/3.0.0/uri/rfc3986_parser.rb:15:in `split'
        from /usr/local/lib/ruby/3.0.0/uri/rfc3986_parser.rb:72:in `parse'
require 'package'
        from /usr/local/lib/ruby/3.0.0/uri/common.rb:171:in `parse'
        from /usr/local/bin/crew:622:in `download'
        from /usr/local/bin/crew:1084:in `install'
        from /usr/local/bin/crew:1072:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1069:in `each'
        from /usr/local/bin/crew:1069:in `resolve_dependencies'
        from /usr/local/bin/crew:960:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1318:in `block in install_command'
        from /usr/local/bin/crew:1312:in `each'
        from /usr/local/bin/crew:1312:in `install_command'
        from /usr/local/bin/crew:1408:in `<main>'
/usr/local/lib/ruby/3.0.0/uri/rfc3986_parser.rb:16:in `split': undefined method `to_str' for nil:NilClass (NoMethodError)
        from /usr/local/lib/ruby/3.0.0/uri/rfc3986_parser.rb:72:in `parse'
        from /usr/local/lib/ruby/3.0.0/uri/common.rb:171:in `parse'
        from /usr/local/bin/crew:622:in `download'
        from /usr/local/bin/crew:1084:in `install'
        from /usr/local/bin/crew:1072:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1069:in `each'
        from /usr/local/bin/crew:1069:in `resolve_dependencies'
        from /usr/local/bin/crew:960:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1318:in `block in install_command'
        from /usr/local/bin/crew:1312:in `each'
        from /usr/local/bin/crew:1312:in `install_command'
        from /usr/local/bin/crew:1408:in `<main>'
```

**Comment by uberhacker** [comment]
This is because firefox is not compatible with arm systems.
