### ISSUE TITLE
[rust] Unable to build on i686

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#6190]
```
$ crew build rust
rust: Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.
Downloading source...
Building from source, this may take a while...
Rename all *.la files to *.la_tmp
Preconfiguring package...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21102  100 21102    0     0  40706      0 --:--:-- --:--:-- --:--:-- 93371
info: downloading installer
info: profile set to 'minimal'
info: setting default host triple to i686-unknown-linux-gnu
info: syncing channel updates for 'stable-i686-unknown-linux-gnu'
thread 'main' panicked at 'range start index 355 out of range for slice of length 32', /cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.2/src/util_libc.rs:65:24
stack backtrace:
   0: 0x77365023 - std::backtrace_rs::backtrace::libunwind::trace::h7fd0e141e2d906ca
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1: 0x77365023 - std::backtrace_rs::backtrace::trace_unsynchronized::h1eca8ded787c5b24
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: 0x77365023 - std::sys_common::backtrace::_print_fmt::h4cb0f8f7cda4d345
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3: 0x77365023 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2579a3d2b4303078
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4: 0x76f78164 - core::fmt::write::h02e8615e652766ba
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5: 0x773648de - std::io::Write::write_fmt::h92c644d2cf74e57f
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6: 0x77364300 - std::sys_common::backtrace::_print::h9b13230a85311925
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7: 0x77364300 - std::sys_common::backtrace::print::h5482833abe329a2b
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8: 0x77364300 - std::panicking::default_hook::{{closure}}::h68d5f6db0f5d7902
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9: 0x773638c6 - std::panicking::default_hook::h82ae8b9a767d7b31
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10: 0x76f15f08 - rustup::currentprocess::with::{{closure}}::{{closure}}::h30fa267c30e0f5f6
  11: 0x773634ca - std::panicking::rust_panic_with_hook::hc3227ec8c33f6507
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:595:17
  12: 0x77382bb2 - std::panicking::begin_panic_handler::{{closure}}::h0408582b591d5da8
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:497:13
  13: 0x77382b1a - std::sys_common::backtrace::__rust_end_short_backtrace::h8bfb2d3fce40ba2b
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  14: 0x77382aa1 - rust_begin_unwind
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  15: 0x76effcf5 - core::panicking::panic_fmt::h50032c7c716249f8
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
  16: 0x76f0016f - core::slice::index::slice_start_index_len_fail::hf81767729ae36c6a
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/slice/index.rs:34:5
  17: 0x7707c7b8 - <rand_core::os::OsRng as rand_core::RngCore>::try_fill_bytes::hbe5b92d8708ff51f
  18: 0x7707c2b0 - std::thread::local::fast::Key<T>::try_initialize::h3f6f74dea40548cb
  19: 0x77290a67 - rustup::utils::raw::random_string::h201d9ea95dbc64f4
  20: 0x772902df - rustup::dist::temp::Cfg::new_file_with_ext::hc273008c953d79ae
  21: 0x7727f8c2 - rustup::dist::download::DownloadCfg::download_and_check::h9bc00d4eee4a5de3
  22: 0x7726c7e5 - rustup::dist::dist::dl_v2_manifest::h5b99ca00c2bca783
  23: 0x772649c4 - rustup::dist::dist::try_update_from_dist_::hf3ecf4073184eaa0
  24: 0x77262587 - rustup::install::InstallMethod::install::hc1e63ca148769e65
  25: 0x77260a7f - rustup::toolchain::DistributableToolchain::install_from_dist::ha25600041b01b912
  26: 0x7734f556 - rustup::cli::self_update::install::h47194fb43e6c8495
  27: 0x76f1bf9e - rustup_init::main::h2d77027039d73808
  28: 0x76f15102 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7b25bcc8e42ab05d
  29: 0x76f1d073 - main
  30: 0x76c70699 - __libc_start_main
rust failed to build: `RUSTFLAGS='-Clto=thin' bash ./rustup.sh -y --no-modify-path --default-host i686-unknown-linux-gnu --default-toolchain stable --profile minimal` exited with 1
```

**Comment by uberhacker** [comment]
Since rust is a build dependency for js78, I cannot build that either.

**Comment by uberhacker** [comment]
Debug info below:
```
checking for rust target triplet... 
DEBUG: Creating `/usr/local/tmp/conftestp06b0azx.rs` with content:
DEBUG: | pub extern fn hello() { println!("Hello world"); }
DEBUG: Executing: `/usr/local/share/rustup/toolchains/stable-i686-unknown-linux-gnu/bin/rustc --crate-type staticlib --target=i686-unknown-linux-gnu -o /usr/local/tmp/conftestuerexi6g.rlib /usr/local/tmp/conftestp06b0azx.rs`
DEBUG: The command returned non-zero exit status 101.
DEBUG: Its error output was:
DEBUG: | thread 'rustc' panicked at 'range start index 355 out of range for slice of length 32', /cargo/registry/src/github.com-1285ae84e5963aae/getrandom-0.2.0/src/util_libc.rs:65:24
DEBUG: | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
DEBUG: | 
DEBUG: | error: internal compiler error: unexpected panic
DEBUG: | 
DEBUG: | note: the compiler unexpectedly panicked. this is a bug.
DEBUG: | 
DEBUG: | note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
DEBUG: | 
DEBUG: | note: rustc 1.54.0 (a178d0322 2021-07-26) running on i686-unknown-linux-gnu
DEBUG: | 
DEBUG: | note: compiler flags: --crate-type staticlib
DEBUG: | 
DEBUG: | query stack during panic:
DEBUG: | end of query stack
ERROR: Cannot compile for i686-pc-linux-gnu with /usr/local/share/rustup/toolchains/stable-i686-unknown-linux-gnu/bin/rustc
The target may be unsupported, or you may not have
a rust std library for that target installed. Try:

  rustup target add i686-unknown-linux-gnu

js78 failed to build: `env CFLAGS='-stdlib=libc++ -flto=thin'             RUSTFLAGS='-Clinker-plugin-lto'             RUSTUP_HOME='/usr/local/share/rustup'             CARGO_HOME='/usr/local/share/cargo'             AUTOCONF=/usr/local/bin/autoconf-2.13             CXXFLAGS='-I/usr/local/include/c++/v1/ -flto=thin'
            CC=clang             CXX='clang++ -stdlib=libc++ -I/usr/local/include/c++/v1/ -flto=thin'             AR=llvm-ar NM=llvm-nm RANLIB=llvm-ranlib             LDFLAGS='-lreadline -ltinfo -flto=thin'             ../js/src/configure --prefix=/usr/local             --libdir=/usr/local/lib             --disable-debug             --disable-debug-symbols             --disable-jemalloc             --disable-strip             --enable-readline             --enable-hardening             --enable-linker=lld             --enable-optimize             --enable-release             --enable-lto             --enable-shared-js             --with-intl-api             --with-system-zlib             --without-system-icu             --enable-rust-simd             --with-system-nspr` exited with 1
```

**Comment by satmandu** [comment]
Getting as far as this:
```
rust failed to build: `install -Dm644 /usr/local/tmp/crew/dest/usr/local/share/rustup/toolchains/stable-i686-unknown-linux-gnu/etc/bash_completion.d/cargo /usr/local/tmp/crew/dest/usr/local/share/bash-completion/completions/cargo` exited with 1
```
