### ISSUE TITLE
[crew_launcher] Missing dependency

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#6287]
```
$ crew-launcher add firefox
crew-launcher server daemon with PID 6459 stopped.
identify: error while loading shared libraries: libomp.so: cannot open shared object file: No such file or directory
convert: error while loading shared libraries: libomp.so: cannot open shared object file: No such file or directory
/usr/local/share/crew-launcher/lib/icon_finder.rb:14:in `system': Command failed with exit 127: convert (RuntimeError)
        from /usr/local/share/crew-launcher/lib/icon_finder.rb:14:in `convert_img'
        from /usr/local/share/crew-launcher/lib/icon_finder.rb:39:in `find'
        from /usr/local/bin/crew-launcher:73:in `CreateProfile'
        from /usr/local/bin/crew-launcher:107:in `InstallPWA'
        from /usr/local/bin/crew-launcher:216:in `<main>'
```
If we can figure out how to NOT depend on llvm, that would be better.

**Comment by satmandu** [comment]
libomp is only 1Mb.

The ur-issue here is still handling dependencies on small parts of other packages.
