### ISSUE TITLE
Invalid URI Error when trying to install core packages (glibc)

### ISSUE THREAD

**Issue by Polytelus** [skycocker/chromebrew#6298]
Whenever the default command to install `curl -Ls git.io/vddgY | bash` is issued, **ruby** gives the following error:

```
glibc: The GNU C Library project provides the core libraries for GNU/Linux systems.
/usr/local/lib64/ruby/3.0.0/uri/rfc3986_parser.rb:18:in `rescue in split': bad URI(is not URI?): nil (URI::InvalidURIError)
        from /usr/local/lib64/ruby/3.0.0/uri/rfc3986_parser.rb:15:in `split'
        from /usr/local/lib64/ruby/3.0.0/uri/rfc3986_parser.rb:72:in `parse'
        from /usr/local/lib64/ruby/3.0.0/uri/common.rb:171:in `parse'
        from /usr/local/bin/crew:621:in `download'
        from /usr/local/bin/crew:1210:in `install'
        from /usr/local/bin/crew:1190:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1187:in `each'
        from /usr/local/bin/crew:1187:in `resolve_dependencies'
        from /usr/local/bin/crew:1078:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1455:in `block in install_command'
        from /usr/local/bin/crew:1450:in `each'
        from /usr/local/bin/crew:1450:in `install_command'
        from /usr/local/bin/crew:1543:in `<main>'
/usr/local/lib64/ruby/3.0.0/uri/rfc3986_parser.rb:16:in `split': undefined method `to_str' for nil:NilClass (NoMethodError)
        from /usr/local/lib64/ruby/3.0.0/uri/rfc3986_parser.rb:72:in `parse'
        from /usr/local/lib64/ruby/3.0.0/uri/common.rb:171:in `parse'
        from /usr/local/bin/crew:621:in `download'
        from /usr/local/bin/crew:1210:in `install'
        from /usr/local/bin/crew:1190:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1187:in `each'
        from /usr/local/bin/crew:1187:in `resolve_dependencies'
        from /usr/local/bin/crew:1078:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1455:in `block in install_command'
        from /usr/local/bin/crew:1450:in `each'
        from /usr/local/bin/crew:1450:in `install_command'
        from /usr/local/bin/crew:1543:in `<main>'

```
This error alone doesn't let the script continue, and it's the first package right after the package list for install appears.
Chromebrew can't install because of this. Help is appreciated.

CROS Version: `R93-14092.46.0 (Stable)`
Chromebrew: `1.17.1`
Model: `Samsung NP370E4J-BW2BR (Using **rammus** Recovery bin, Chromehack)`
Architecture: `x86_64`

**Comment by supechicken** [comment]
Can you provide the output of `crew const LIBC_VERSION`?

**Comment by Polytelus** [comment]
Can confirm, it works!
