### ISSUE TITLE
[glibc] Unable to install due to wrong LIBC_VERSION

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#6307]
```
$ crew upgrade
Updating packages...
glibc: The GNU C Library project provides the core libraries for GNU/Linux systems.
Performing pre-flight checks...
/usr/local/lib/ruby/3.0.0/uri/rfc3986_parser.rb:18:in `rescue in split': bad URI(is not URI?): nil (URI::InvalidURIError)
        from /usr/local/lib/ruby/3.0.0/uri/rfc3986_parser.rb:15:in `split'
        from /usr/local/lib/ruby/3.0.0/uri/rfc3986_parser.rb:72:in `parse'
        from /usr/local/lib/ruby/3.0.0/uri/common.rb:171:in `parse'
        from /usr/local/bin/crew:621:in `download'
        from /usr/local/bin/crew:1210:in `install'
        from /usr/local/bin/crew:1081:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:607:in `block in upgrade'
        from /usr/local/bin/crew:602:in `each'
        from /usr/local/bin/crew:602:in `upgrade'
        from /usr/local/bin/crew:1527:in `upgrade_command'
        from /usr/local/bin/crew:1543:in `<main>'
/usr/local/lib/ruby/3.0.0/uri/rfc3986_parser.rb:16:in `split': undefined method `to_str' for nil:NilClass (NoMethodError)
        from /usr/local/lib/ruby/3.0.0/uri/rfc3986_parser.rb:72:in `parse'
        from /usr/local/lib/ruby/3.0.0/uri/common.rb:171:in `parse'
        from /usr/local/bin/crew:621:in `download'
        from /usr/local/bin/crew:1210:in `install'
        from /usr/local/bin/crew:1081:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:607:in `block in upgrade'
        from /usr/local/bin/crew:602:in `each'
        from /usr/local/bin/crew:602:in `upgrade'
        from /usr/local/bin/crew:1527:in `upgrade_command'
        from /usr/local/bin/crew:1543:in `<main>'
```
```
$ crew const LIBC_VERSION
LIBC_VERSION=2
```
Should be 2.23

**Comment by satmandu** [comment]
@supechicken I think you broke this when you modified `lib/const.rb` to have `LIBC_VERSION = %x[/#{ARCH_LIB}/libc.so.6][/version ([\d.]+)\./, 1]`

**Comment by supechicken** [comment]
The present one works for me:
```
chronos@localhost / $ crew const LIBC_VERSION
LIBC_VERSION=2.32
```
There may have been some differences in output between versions?

**Comment by uberhacker** [comment]
Yes, there is a slight difference and unless you have the actual hardware to test, there is no way you would have know.  For the record, the difference is `,` vs `.`.  See below:
armv7l:
```
GNU C Library (Gentoo 2.27-r15 p3) stable release version 2.27.
```
i686:
```
GNU C Library (Gentoo 2.23-r4 p6) stable release version 2.23, by Roland McGrath et al.
```
x86_64:
```
GNU C Library (Gentoo 2.32-r14 p8) stable release version 2.32.
```
