### ISSUE TITLE
Still unable to build binaries

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#6539]
```
ERROR: sizeof(size_t) doesn't match GLIB_SIZEOF_SIZE_T.
       You probably need to set PKG_CONFIG_LIBDIR
       to point to the right pkg-config files for your
       build target

/usr/local/lib/crew/lib/package.rb:181:in `system': Command failed with exit 1: bash
/usr/local/lib/crew/lib/package.rb:189:in `rescue in system': undefined method `join' for "./configure --prefix=/usr/local --libdir=/usr/local/lib --disable-stack-protector":String (NoMethodError)
        from /usr/local/lib/crew/lib/package.rb:179:in `system'
        from /usr/local/lib/crew/packages/qemu.rb:32:in `build'
        from /usr/local/bin/crew:868:in `block in build_and_preconfigure'
        from /usr/local/bin/crew:854:in `chdir'
        from /usr/local/bin/crew:854:in `build_and_preconfigure'
        from /usr/local/bin/crew:1391:in `build_package'
        from /usr/local/bin/crew:1368:in `resolve_dependencies_and_build'
        from /usr/local/bin/crew:1526:in `block in build_command'
        from /usr/local/bin/crew:1522:in `each'
        from /usr/local/bin/crew:1522:in `build_command'
        from /usr/local/bin/crew:1672:in `<main>'
/usr/local/lib/crew/lib/package.rb:181:in `system': Command failed with exit 1: bash (RuntimeError)
        from /usr/local/lib/crew/lib/package.rb:181:in `system'
        from /usr/local/lib/crew/packages/qemu.rb:32:in `build'
        from /usr/local/bin/crew:868:in `block in build_and_preconfigure'
        from /usr/local/bin/crew:854:in `chdir'
        from /usr/local/bin/crew:854:in `build_and_preconfigure'
        from /usr/local/bin/crew:1391:in `build_package'
        from /usr/local/bin/crew:1368:in `resolve_dependencies_and_build'
        from /usr/local/bin/crew:1526:in `block in build_command'
        from /usr/local/bin/crew:1522:in `each'
        from /usr/local/bin/crew:1522:in `build_command'
        from /usr/local/bin/crew:1672:in `<main>'
```

**Comment by uberhacker** [comment]
```
Rename all *.la files to *.la_tmp
/bin/sh: 1: Syntax error: "(" unexpected
/usr/local/lib/crew/lib/package.rb:174:in `system': Command failed with exit 2: bash -e -c "sed -e "/gperf --/s/gperf --/gperf --includes --/" -e "/gperf --/s/cap_lookup_name(/cap_dummy(/" -i libcap/Makefile"                                                                                                                                                                    
libcap failed to build: `sed -e "/gperf --/s/gperf --/gperf --includes --/" -e "/gperf --/s/cap_lookup_name(/cap_dummy(/" -i libcap/Makefile` exited with 2
```

**Comment by satmandu** [comment]
Sigh. Needs more escaping...
