### ISSUE TITLE
rsync cannot find libxxhash.so.0

### ISSUE THREAD

**Issue by esprout** [skycocker/chromebrew#6747]
I'm trying to update my M98 system.  rsync was missing.  I manually installed it, bit it cannot find libxxhash.so.0.  I tried installing xxhash, which appeared to install properly, but libxxhash.so.0 does not seem to reside in the xxhash package.

I had previously updated glibc to 2.33 on this system.

chronos@localhost /dev/shm $ CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=glibc_test CREW_TESTING=1 crew upgrade glibc
glibc: The GNU C Library project provides the core libraries for GNU/Linux systems.
Updating glibc...
Performing pre-flight checks...
Precompiled binary available, downloading...
[#########################################################                                                   ]  21.50 MB[####[############################################################################################################]  21.50 MB 100%
Glibc archive downloaded.
Unpacking 'tpxz' archive using 'tar', this may take a while...
Removing since upgrade or reinstall...
Glibc removed!
Performing pre-install...
Performing install...
/usr/local/bin/rsync: error while loading shared libraries: libxxhash.so.0: cannot open shared object file: No such file or directory
rsync is not working. Please (re)install it with 'crew remove musl_zstd zstd ; crew install musl_zstd ; crew install rsync'
sh: error while loading shared libraries: /usr/local/lib64/libc.so.6: file too short
/usr/local/sbin/ldconfig: File /usr/local/lib64/libc-2.33.so is empty, not checked.
/usr/local/sbin/ldconfig: File /usr/local/lib64/libc.so.6 is empty, not checked.
Performing post-install for glibc...
sh: error while loading shared libraries: /usr/local/lib64/libc.so.6: file too short
/usr/local/lib/crew/packages/glibc.rb:588:in `postinstall': undefined method `chomp' for nil:NilClass (NoMethodError)
        from /usr/local/bin/crew:936:in `block (2 levels) in post_install'
        from /usr/local/bin/crew:934:in `chdir'
        from /usr/local/bin/crew:934:in `block in post_install'
        from /usr/local/lib64/ruby/3.0.0/tmpdir.rb:96:in `mktmpdir'
        from /usr/local/bin/crew:933:in `post_install'
        from /usr/local/bin/crew:1267:in `block in resolve_dependencies_and_install'
        from /usr/local/bin/crew:1265:in `each'
        from /usr/local/bin/crew:1265:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:585:in `upgrade'
        from /usr/local/bin/crew:1783:in `block in upgrade_command'
        from /usr/local/bin/crew:1778:in `each'
        from /usr/local/bin/crew:1778:in `upgrade_command'
        from /usr/local/bin/crew:1801:in `<main>'

**Comment by esprout** [comment]
I fixed this with some combination of removal and reinstall:

crew remove musl_zstd zstd xxhash lz4 popt
crew install musl_zstd ; crew install zstd
crew install rsync

I think that sequence of commands did the trick.

Probably removing xxhash and let rsync install take care of the dependency was the key.
