### ISSUE TITLE
Unable to add new crew-launcher app

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#6851]
```
$ crew-launcher add signal_desktop
/usr/local/share/crew-launcher/lib/desktop_file.rb:18:in `split': invalid byte sequence in UTF-8 (ArgumentError)
        from /usr/local/share/crew-launcher/lib/desktop_file.rb:18:in `parse'
        from /usr/local/bin/crew-launcher:62:in `CreateProfile'
        from /usr/local/bin/crew-launcher:107:in `InstallPWA'
        from /usr/local/bin/crew-launcher:216:in `<main>'
```

**Comment by satmandu** [comment]
I'm hoping this isn't a ruby 3.1.1 regression. (All ruby tests passed.)

**Comment by supechicken** [comment]
Seems that the desktop file `signal` is encoded with `ascii`, not `utf-8` (which is expected by `crew-launcher`). Maybe try the following (convert encoding to `utf8` before parsing the desktop entry file):
```shell
sed -i "s/File.read(path, encoding: Encoding::UTF_8)/File.read(path).encode('UTF-8')/g" /usr/local/share/crew-launcher/lib/desktop_file.rb
```

**Comment by satmandu** [comment]
Could we have the UTF-8 conversion done by the crew_desktop script?

**Comment by uberhacker** [comment]
@supechicken: That didn't fix it.
```
chronos@localhost ~/chromebrew/packages (master *%=)$ sed -i "s/File.read(path, encoding: Encoding::UTF_8)/File.read(path).encode('UTF-8')/g" /usr/local/share/crew-launcher/lib/desktop_file.rb
chronos@localhost ~/chromebrew/packages (master *%=)$ crew-launcher add signal_desktop
crew-launcher server daemon with PID 3723 stopped.
/usr/local/share/crew-launcher/lib/desktop_file.rb:18:in `split': invalid byte sequence in UTF-8 (ArgumentError)
        from /usr/local/share/crew-launcher/lib/desktop_file.rb:18:in `parse'
        from /usr/local/bin/crew-launcher:62:in `CreateProfile'
        from /usr/local/bin/crew-launcher:107:in `InstallPWA'
        from /usr/local/bin/crew-launcher:216:in `<main>'
```

**Comment by uberhacker** [comment]
I think the problem is the discovery.  It finds `/usr/local/share/Signal/signal-desktop` instead `/usr/local/share/applications/signal-desktop.desktop`.  The error is the result of the binary file.
