### ISSUE TITLE
Not able to run java file

### ISSUE THREAD

**Issue by Sasytoremember** [skycocker/chromebrew#7027]
Java complains about Chrome OS not letting it run the JVM.

shell
java -jar TLauncher-2.841.jar

Output:
-------------------------------------------------------------------
[Downloader2] Loaded configuration: normal
[Downloader2] Files in queue 1
[Downloader2] Starting download 1 files...
[D#1] >  http://res.tlauncher.org/b/client/jre/linux/jre-8u281-linux-x64.zip 
rename from /home/chronos/user/.tlauncher/jvms/jre1.8.0_281_temp to /home/chronos/user/.tlauncher/jvms/jre1.8.0_281
[Bootstrapper] createLauncher
[Bootstrapper] choose jvm:/home/chronos/user/.tlauncher/jvms/jre1.8.0_281/bin/java
[Bootstrapper] validate files
[Bootstrapper] end validated files
[Bootstrapper] Starting launcher...
[Double running] clear time label
java.io.IOException: Cannot run program "/home/chronos/user/.tlauncher/jvms/jre1.8.0_281/bin/java" (in directory "."): error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at net.minecraft.launcher.process.JavaProcessLauncher.start(JavaProcessLauncher.java:27)
        at org.tlauncher.tlauncher.rmo.Bootstrapper.start(Bootstrapper.java:404)
        at org.tlauncher.tlauncher.rmo.Bootstrapper.main(Bootstrapper.java:123)
Caused by: java.io.IOException: error=13, Permission denied
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 3 more
problem with preparing boostrapper
Good bye!
[Double running] clear time label
flush now

sysinfo:
***
- Architecture: `x86_64` (`x86_64`)
- Kernel version: `5.10.110-15761-ge1d8c2d6a5fb`

- Chromebrew version: `1.23.15`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: ``

- OS variant: `Chrome OS`
- OS version: `reven-release/R102-14695.9.0`
- OS channel: `dev-channel`
***

do this
- [ ] step one: Install Java. (crew install jdk)
- [ ] step two: Run a Java JAR file. (java -jar (filename).jar)

**Comment by uberhacker** [comment]
@Sasytoremember: We do not support the dev channel.  From README.md:
```
The beta, dev, and Canary channels are not supported and should not be used with Chromebrew. Failure to take notice of this will cause major issues with your Chromebrew installation.
```
If you switch back to the stable channel and still have issues, let us know.

**Comment by uberhacker** [comment]
Also, the HOME directory is now mounted without exec privileges which would explain the error.  You might try it in `/usr/local/tmp` to test if it executes.  But again, we cannot offer support if you remain in the dev channel.

**Comment by Sasytoremember** [comment]
Alright, thanks dude. Didn't know that chromeos blocked execution privileges in the home folders, thanks!

**Comment by Sasytoremember** [comment]
How do I change the VM's directory?

**Comment by uberhacker** [comment]
You could try symlink like:
```
mkdir /usr/local/.tlauncher
ln -s /usr/local/.tlauncher /home/chronos/user/.tlauncher
```

**Comment by Sasytoremember** [comment]
Stuff when I applied link: ( sorry, i don't know how to solve simple things like this. )
[SimpleConfiguration] /root/.tlauncher/tlauncher-2.0.properties file not exists
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /root/.minecraft/logs/tlauncher/boot_05_09_2022_16_16_26.log (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
        at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
        at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
        at org.tlauncher.util.U.initializeLoggerU(U.java:593)
        at org.tlauncher.tlauncher.rmo.Bootstrapper.main(Bootstrapper.java:71)

-------------------------------------------------------------------
can't delete file
java.io.IOException: No such file or directory
at java.io.UnixFileSystem.createFileExclusively(Native Method)
at java.io.File.createNewFile(File.java:1023)
at org.tlauncher.util.FileUtil.createFile(FileUtil.java:299)
at org.tlauncher.util.FileUtil.writeFile(FileUtil.java:70)
at org.tlauncher.util.TlauncherUtil.createTimeStart(TlauncherUtil.java:360)
at org.tlauncher.tlauncher.rmo.Bootstrapper.testDoubleRunning(Bootstrapper.java:155)
at org.tlauncher.tlauncher.rmo.Bootstrapper.main(Bootstrapper.java:92)

[SimpleConfiguration] Cannot store values!
java.io.FileNotFoundException: /root/.tlauncher/tlauncher-2.0.properties (No such file or directory)
at java.io.FileOutputStream.open0(Native Method)
at java.io.FileOutputStream.open(FileOutputStream.java:270)
at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
at org.tlauncher.tlauncher.configuration.SimpleConfiguration.save(SimpleConfiguration.java:231)
at org.tlauncher.tlauncher.configuration.SimpleConfiguration.store(SimpleConfiguration.java:236)
at org.tlauncher.tlauncher.configuration.SimpleConfiguration.set(SimpleConfiguration.java:80)
at org.tlauncher.tlauncher.configuration.SimpleConfiguration.set(SimpleConfiguration.java:85)
at org.tlauncher.tlauncher.rmo.Bootstrapper.createAndValidateWorkDir(Bootstrapper.java:230)
at org.tlauncher.tlauncher.rmo.Bootstrapper.main(Bootstrapper.java:98)

[SimpleConfiguration] Cannot store values!
java.io.FileNotFoundException: /root/.tlauncher/tlauncher-2.0.properties (No such file or directory)
at java.io.FileOutputStream.open0(Native Method)
at java.io.FileOutputStream.open(FileOutputStream.java:270)
at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
at org.tlauncher.tlauncher.configuration.SimpleConfiguration.save(SimpleConfiguration.java:231)
at org.tlauncher.tlauncher.configuration.SimpleConfiguration.store(SimpleConfiguration.java:236)
at org.tlauncher.tlauncher.configuration.SimpleConfiguration.set(SimpleConfiguration.java:80)
at org.tlauncher.tlauncher.rmo.Bootstrapper.valitdateKB4515384(Bootstrapper.java:164)
at org.tlauncher.tlauncher.rmo.Bootstrapper.main(Bootstrapper.java:100)

Exception in thread "main" java.lang.IllegalArgumentException: Specified path is not a directory: /root/.tlauncher/jvms
        at org.tlauncher.util.FileUtil.deleteDirectory(FileUtil.java:255)
        at org.tlauncher.tlauncher.rmo.Bootstrapper.fixedOnce(Bootstrapper.java:209)
        at org.tlauncher.tlauncher.rmo.Bootstrapper.main(Bootstrapper.java:131)

**Comment by uberhacker** [comment]
Don't use sudo or shell in as the root user.  I see `/root/.launcher`.  That should be `/home/chronos/user/.launcher`.  As a general rule, you should never need to run anything with elevated privileges, even installers.
