### ISSUE TITLE
Unable to upgrade jdk8

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#763]
```
$ crew upgrade
Updating packages...
(i) jdk8: The JDK is a development environment for building applications, applets, and components using the Java programming language.
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
version 8u131
Precompiled binary available, downloading...
--2017-06-19 08:39:23--  http://javadl.oracle.com/webapps/download/AutoDL?BundleId=220305_d54c1d3a095b4ff2b6607d096fa80163
Resolving javadl.oracle.com... 137.254.120.23
Connecting to javadl.oracle.com|137.254.120.23|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://sdlc-esd.oracle.com/ESD6/JSCDL/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jre-8u131-linux-x64.tar.gz?GroupName=JSC&FilePath=/ESD6/JSCDL/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jre-8u131-linux-x64.tar.gz&BHost=javadl.sun.com&File=jre-8u131-linux-x64.tar.gz&AuthParam=1497880764_d6b1fb882a621bd0c820508630c132f9&ext=.gz [following]
--2017-06-19 08:39:24--  http://sdlc-esd.oracle.com/ESD6/JSCDL/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jre-8u131-linux-x64.tar.gz?GroupName=JSC&FilePath=/ESD6/JSCDL/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jre-8u131-linux-x64.tar.gz&BHost=javadl.sun.com&File=jre-8u131-linux-x64.tar.gz&AuthParam=1497880764_d6b1fb882a621bd0c820508630c132f9&ext=.gz
Resolving sdlc-esd.oracle.com... 23.218.156.10, 23.218.156.40
Connecting to sdlc-esd.oracle.com|23.218.156.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 75920010 (72M) [application/x-gzip]
Saving to: 'AutoDL'

AutoDL                                               100%[====================================================================================================================>]  72.40M  3.96MB/s    in 23s     

2017-06-19 08:39:47 (3.16 MB/s) - 'AutoDL' saved [75920010/75920010]

Archive downloaded
Unpacking archive, this may take a while...
Removing since upgrade...
Jdk8 removed!
Installing...
/usr/local/lib/ruby/2.4.0/fileutils.rb:468:in `rename': No such file or directory @ rb_file_s_rename - (dlist, /usr/local/etc/crew/meta/jdk8.directorylist) (Errno::ENOENT)
        from /usr/local/lib/ruby/2.4.0/fileutils.rb:468:in `block in mv'
        from /usr/local/lib/ruby/2.4.0/fileutils.rb:1460:in `block in fu_each_src_dest'
        from /usr/local/lib/ruby/2.4.0/fileutils.rb:1476:in `fu_each_src_dest0'
        from /usr/local/lib/ruby/2.4.0/fileutils.rb:1458:in `fu_each_src_dest'
        from /usr/local/lib/ruby/2.4.0/fileutils.rb:457:in `mv'
        from /usr/local/bin/crew:415:in `block in install_package'
        from /usr/local/bin/crew:414:in `chdir'
        from /usr/local/bin/crew:414:in `install_package'
        from /usr/local/bin/crew:558:in `install'
        from /usr/local/bin/crew:429:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:315:in `block in upgrade'
        from /usr/local/bin/crew:312:in `each'
        from /usr/local/bin/crew:312:in `upgrade'
        from /usr/local/bin/crew:712:in `<main>'
```

**Comment by uberhacker** [comment]
Fixed in PR #764.
